# Created on Fri Dec 19 15:48:27  2025
# SCMT Configuration File for IntelliStar 1 Domestic
# Generated by IntelliStar Config Generator by @sspwxr (raii)
Log.info('scmt config started')
#
def scmtRemove(key):
    try:
        dsm.remove(key)
    except:
        pass
#

#
# Beginning of SCMT deployment
import os
dsm.set('scmt_configType', 'domestic',0)
dsm.set('scmt.ProductTypes',['Animated_Logo_Sponsor','Copy_Split','Custom','Logo_Sponsor', 'Dealer'], 0)
#
wxdata.setInterestList('airportId','1',[])
wxdata.setInterestList('coopId','1',['71801004', '71196000', '71807000'])
wxdata.setInterestList('indexId','1',[''])
#wxdata.setInterestList('pollenId','1',[])
wxdata.setInterestList('obsStation','1',['T71807000'])
wxdata.setInterestList('climId','1',['CNLI71196'])
wxdata.setInterestList('zone','1',['021100', '025300', '021400'])
#wxdata.setInterestList('aq','1',[])
wxdata.setInterestList('skiId','1',[])
wxdata.setInterestList('county','1',['CCC999'])
dsm.set('Config.1.countyNameList',[('CCC999', 'Dummy  County')], 0)
dsm.set('dmaCode','None', 0)
dsm.set('secondaryObsStation','T71807000', 0)
dsm.set('primaryClimoStation','CNLI71196', 0)
dsm.set('primaryIndexId','', 0)
dsm.set('ThemeOverride','standard', 0)
dsm.set('stateCode','NF', 0)
dsm.set('primaryAqStation','None', 0)
dsm.set('primPollenSiteName','Dildo', 0)
dsm.set('primaryCoopId','71801004', 0)
dsm.set('Config.1.PlaylistOverride','DefaultUS', 0)
dsm.set('wda','', 0)
dsm.set('primaryCounty','CCC999', 0)
dsm.set('primaryObsStation','T71807000', 0)
dsm.set('hasTraffic',0, 0)
dsm.set('primaryPollenStation','', 0)
dsm.set('Config.1.Clock','scmt.clock', 0)
dsm.set('primaryLon',-53.557, 0)
dsm.set('primaryLat',47.569, 0)
dsm.set('primaryForecastName','Dildo', 0)
dsm.set('primaryZone','021100', 0)
dsm.set('climoRegion','3', 0)
dsm.set('Config.1.SevereClock','scmt_severe.clock', 0)
dsm.set('countryCode','CA', 0)
#
scmtRemove('Config.1.Tag.General.airportData')
d = twc.Data()
d.airportId = []
d.airportLocName = []
d.obsStation = []
dsm.set('Config.1.Tag.General.airportData', d, 0, 1)
#
#
d = twc.Data()
d.obsStation = ['T71807000']
d.locName = ['Dildo']
d.elementDuration = 6
dsm.set('Config.1.Cc_CurrentConditions', d, 0, 1)
#
d = twc.Data()
d.obsStation = ['T71807000']
d.locName = ['Dildo']
d.activeVocalCue = 1
d.activeVocal = 1
dsm.set('Config.1.Local_CurrentConditions', d, 0, 1)
#
d = twc.Data()
d.obsStation = ['T71807000']
d.schedule = [((11,20,16,0,0), (11,23,16,0,0)),((12,16,16,0,0), (1,4,16,0,0)),((5,25,16,0,0), (9,1,16,0,0)),]
d.coopId = '71801004'
dsm.set('Config.1.Local_SchoolDayWeather', d, 0, 1)
#
d = twc.Data()
d.climId = 'CNLI71196'
d.latitude = 47.569
d.longitude = -53.557
dsm.set('Config.1.Ldl_SunriseSunset', d, 0, 1)
#
d = twc.Data()
d.obsStation = ['T71807000']
d.timeDuration = 5
d.tempDuration = 8
dsm.set('Config.1.TimeTemp_Default', d, 0, 1)
#
d = twc.Data()
d.obsStation = ['T71807000']
d.obsLocName = ['Dildo']
dsm.set('Config.1.Ldl_CurrentApparentTemp', d, 0, 1)
#
d = twc.Data()
d.obsStation = ['T71807000']
d.obsLocName = ['Dildo']
dsm.set('Config.1.Ldl_CurrentMTDPrecip', d, 0, 1)
#
d = twc.Data()
d.obsStation = 'T71807000'
d.climId = ['CNLI71196']
d.latitude = 47.569
d.longitude = -53.557
d.locName = 'DILDO'
d.coopId = '71801004'
dsm.set('Config.1.Local_Climatology', d, 0, 1)
#
d = twc.Data()
d.obsStation = ['T71807000']
d.locName = ['Grates Cove', 'Bonavista', 'WINTERLAND BRANCH HILL']
dsm.set('Config.1.Local_LocalObservations', d, 0, 1)
#
d = twc.Data()
d.locName = 'Dildo'
d.coopId = '71801004'
dsm.set('Config.1.Fcst_ExtendedForecast', d, 0, 1)
#
d = twc.Data()
d.location = 'DILDO'
d.coopId = '71801004'
d.activeVocalCue = 1
d.activeVocal = 1
dsm.set('Config.1.Local_ExtendedForecast', d, 0, 1)
#
d = twc.Data()
d.locName = 'DILDO'
d.coopId = '71801004'
d.activeVocalCue = 1
dsm.set('Config.1.Local_7DayForecast', d, 0, 1)
#
d = twc.Data()
d.minPageDuration = 8
d.locName = 'DILDO'
d.coopId = '71801004'
d.maxPageDuration = 14
d.activeVocalCue = 1
d.activeVocal = 1
dsm.set('Config.1.Local_TextForecast', d, 0, 1)
#
d = twc.Data()
d.locName = 'Dildo'
d.coopId = '71801004'
dsm.set('Config.1.Fcst_ExtendedForecast', d, 0, 1)
#
d = twc.Data()
d.locName = 'Dildo'
d.coopId = '71801004'
dsm.set('Config.1.Fcst_TextForecast', d, 0, 1)
#
d = twc.Data()
d.locName = 'Dildo'
d.coopId = '71801004'
dsm.set('Config.1.Fcst_DaypartForecast', d, 0, 1)
#
ds.commit()
dsm.set('Config.1.Ldl_HourlyForecast', d, 0, 1)
dsm.set('Config.1.Ldl_Shortcast', d, 0, 1)
dsm.set('Config.1.Ldl_SummaryForecast', d, 0, 1)
#

#
Log.info('scmt config completed')
# Finished generation on Fri Dec 19 15:48:27  2025