"""
IntelliStar 1 Domestic (Pre-WATT, 2003-2013) Configuration Generator

This module generates Python configuration scripts for the IntelliStar 1 Domestic
systems used by The Weather Channel before the 2013 Enhanced/WATT rebrand.

Fonts: Interstate-Bold, Interstate-Black, Interstate-BoldCondensed, Interstate-BlackCondensed
"""
from __future__ import annotations
from typing import TYPE_CHECKING, Sequence

from utils.map_utils import (
    latlon_to_pixel,
    clamp_mapcut_coordinate,
    DOMESTIC_PROJECTION,
)

if TYPE_CHECKING:
    from main import AggregatedConfig
    from utils.LFRecord_operations import LocationRecord


def quote_list(items: Sequence[str | None]) -> str:
    return ", ".join(f"'{item}'" for item in items if item)


def compile_header() -> str:
    return """# IntelliStar 1 Domestic Configuration
# Generated by IntelliStar Config Generator
Log.info('scmt config started')
#
def scmtRemove(key):
    try:
        dsm.remove(key)
    except:
        pass
#
# Beginning of SCMT deployment
import os
dsm.set('scmt_configType', 'domestic',0)
dsm.set('scmt.ProductTypes',['Animated_Logo_Sponsor','Copy_Split','Custom','Logo_Sponsor', 'Dealer'], 0)
#
scmtRemove('Config.1.Ldl_TrafficTripTimes')
scmtRemove('Config.1.Ldl_TrafficReport')
scmtRemove('Config.1.Ldl_Almanac.0')
scmtRemove('Config.1.Ldl_DailyForecast.0')
scmtRemove('Config.1.Ldl_TravelForecast.0')
dsm.set('Scmt.PlatformType', 'IntelliStar', 0)
#
# Sound effect schedule
scmtRemove('Config.1.SoundFxSchedule')
d = twc.Data()
d.OffTimes = ((0,23),)
dsm.set('Config.1.SoundFxSchedule', d, 0, 1)
#
# National LDL Map Removes
scmtRemove('Config.1.NationalLdl_HourlyForecast.0')
scmtRemove('Config.1.NationalLdl_HourlyForecast.1')
scmtRemove('Config.1.NationalLdl_HourlyForecast.2')
scmtRemove('Config.1.NationalLdl_HourlyForecast.3')
scmtRemove('Config.1.NationalLdl_HourlyForecast.4')
scmtRemove('Config.1.NationalLdl_HourlyForecast.5')
scmtRemove('Config.1.NationalLdl_TextForecast.0')
scmtRemove('Config.1.NationalLdl_36HourForecast.0')
scmtRemove('Config.1.NationalLdl_36HourForecast.1')
scmtRemove('Config.1.NationalLdl_36HourForecast.2')
scmtRemove('Config.1.NationalLdl_36HourForecast.3')
scmtRemove('Config.1.NationalLdl_36HourForecast.4')
scmtRemove('Config.1.NationalLdl_36HourForecast.5')
scmtRemove('Config.1.NationalLdl_RadarSatellite')
scmtRemove('Config.1.NationalLdl_DopplerRadar')
scmtRemove('Config.1.NationalLdl_DaypartForecast')
#
"""


def compile_map_interest_lists(config: "AggregatedConfig") -> str:
    return """#
# MAP INTEREST LISTS
#
wxdata.setInterestList('lambert.us','1',['radarSatellite.us',])
wxdata.setInterestList('mercator.us','1',['radar.us',])
#
wxdata.setInterestList('radarSatellite.us.cuts','1',['Config.1.NationalLdl_RadarSatellite','Config.1.Local_RadarSatelliteComposite',])
wxdata.setInterestList('radar.us.cuts','1',['Config.1.NationalLdl_DopplerRadar','Config.1.Radar_LocalDoppler','Config.1.Local_MetroDopplerRadar','Config.1.Local_RegionalDopplerRadar',])
#
wxdata.setInterestList('mapData','1',['mercator.us','lambert.us',])
#
wxdata.setInterestList('imageData','1',['radarSatellite.us','radar.us',])
# END OF MAPS
# commit for map stuff to avoid missing updates
ds.commit()
#
"""


def compile_map_data(config: "AggregatedConfig") -> str:
    if config.lat is None or config.lon is None:
        return "# MAP DATA SKIPPED - No lat/lon available for primary location\n"

    loc_name = config.name
    lat, lon = config.lat, config.lon

    center_x, center_y = latlon_to_pixel(lat, lon, DOMESTIC_PROJECTION)

    def calc_mapcut(size_w: int, size_h: int) -> tuple[int, int]:
        cut_x = center_x - size_w // 2
        cut_y = center_y - size_h // 2
        return clamp_mapcut_coordinate(cut_x, cut_y, size_w, size_h)

    def calc_datacut(mapcut_x: int, mapcut_y: int, size_w: int, size_h: int) -> tuple[int, int]:
        cx = mapcut_x + size_w // 2
        cy = mapcut_y + size_h // 2
        return (int(cx / 9.4), int(cy / 9.4))

    nldl_doppler_cut = calc_mapcut(1440, 821)
    nldl_doppler_datacut = calc_datacut(nldl_doppler_cut[0], nldl_doppler_cut[1], 1440, 821)

    radar_local_cut = calc_mapcut(1440, 822)
    radar_local_datacut = calc_datacut(radar_local_cut[0], radar_local_cut[1], 1440, 822)

    metro_doppler_cut = calc_mapcut(1440, 960)
    metro_doppler_datacut = calc_datacut(metro_doppler_cut[0], metro_doppler_cut[1], 1440, 960)

    regional_doppler_cut = calc_mapcut(2880, 1644)
    regional_doppler_datacut = calc_datacut(regional_doppler_cut[0], regional_doppler_cut[1], 2880, 1644)

    metro_obs_cut = calc_mapcut(1584, 1056)
    metro_fcst_cut = calc_mapcut(1584, 1056)

    regional_obs_cut = calc_mapcut(5760, 3840)
    regional_fcst_cut = calc_mapcut(5760, 3840)

    radar_sat_cut = calc_mapcut(936, 624)
    radar_sat_datacut = calc_datacut(radar_sat_cut[0], radar_sat_cut[1], 936, 624)

    nldl_satellite_cut = calc_mapcut(1072, 611)
    nldl_satellite_datacut = calc_datacut(nldl_satellite_cut[0], nldl_satellite_cut[1], 1072, 611)

    satellite_cut = calc_mapcut(2196, 1464)
    satellite_datacut = calc_datacut(satellite_cut[0], satellite_cut[1], 2196, 1464)

    return f"""#
# MAP DATA DEFINITIONS
# Generated from primary location coordinates
# Lat: {lat}, Lon: {lon}
# Center pixel: ({center_x}, {center_y})
#
# NationalLdl_DopplerRadar (MAP DATA)
d = twc.Data(mapName='mercator.us.bfg',
             mapcutCoordinate={nldl_doppler_cut},
             mapcutSize=(1440,821),
             mapFinalSize=(193,110),
             mapMilesSize=(134,92),
             datacutType='radar.us',
             datacutCoordinate={nldl_doppler_datacut},
             datacutSize=(176,101),
             dataFinalSize=(193,110),
             dataOffset=(0,0),
             vectors=['mercator.us.ushighways.vg','mercator.us.counties.vg','mercator.us.states.vg','mercator.us.coastlines.vg','mercator.us.statehighways.vg','mercator.us.otherroutes.vg','mercator.us.interstates.vg',],
)
wxdata.setMapData('Config.1.NationalLdl_DopplerRadar', d, 0)
#
d = twc.Data(
  tiffImage = [
             (('locatorDotSmallOutline',0,2,1,),(((101,55),),),),
             (('locatorDotSmall',0,1,0,),(((101,55),),),),
        ],
  textString = [
             (('Interstate-Bold',14,(229,229,229,205),1,0,0,(20,20,20,68),1,0,0,),(((49,61),'{loc_name}',),),),
             (('Interstate-Bold',14,(229,229,229,255),1,0,0,(20,20,20,68),2,0,0,),(((49,61),'{loc_name}',),),),
        ],
  vector = [
             ((6,(20,20,20,96),1,),(('statehighways',),),),
             ((6,(20,20,20,96),1,),(('ushighways',),),),
             ((6,(20,20,20,96),1,),(('interstates',),),),
             ((6,(20,20,20,96),1,),(('otherroutes',),),),
             ((1,(20,20,20,255),2,),(('counties',),),),
             ((2,(20,20,20,255),2,),(('states',),),),
             ((1,(20,20,20,255),2,),(('coastlines',),),),
             ((3,(130,130,130,255),2,),(('statehighways',),),),
             ((3,(130,130,130,255),2,),(('ushighways',),),),
             ((3,(130,130,130,255),2,),(('interstates',),),),
             ((3,(130,130,130,255),2,),(('otherroutes',),),),
             ],
)
dsm.set('Config.1.NationalLdl_DopplerRadar', d, 0)
#
# Radar_LocalDoppler (MAP DATA)
d = twc.Data(mapName='mercator.us.bfg',
             mapcutCoordinate={radar_local_cut},
             mapcutSize=(1440,822),
             mapFinalSize=(240,137),
             mapMilesSize=(134,92),
             datacutType='radar.us',
             datacutCoordinate={radar_local_datacut},
             datacutSize=(176,100),
             dataFinalSize=(240,137),
             dataOffset=(0,0),
             vectors=['mercator.us.ushighways.vg','mercator.us.counties.vg','mercator.us.states.vg','mercator.us.coastlines.vg','mercator.us.statehighways.vg','mercator.us.otherroutes.vg','mercator.us.interstates.vg',],
)
wxdata.setMapData('Config.1.Radar_LocalDoppler', d, 0)
#
d = twc.Data(
  tiffImage = [
             (('locatorDotOutline',0,2,1,),(((120,69),),),),
             (('locatorDot',0,1,0,),(((120,69),),),),
        ],
  textString = [
             (('Interstate-Black',20,(255,255,255,204),1,0,0,(20,20,20,68),1,0,0,),(((50,90),'{loc_name}',),),),
             (('Interstate-Black',20,(255,255,255,255),1,0,0,(20,20,20,68),2,0,0,),(((50,90),'{loc_name}',),),),
        ],
  vector = [
             ((6,(20,20,20,96),1,),(('statehighways',),),),
             ((6,(20,20,20,96),1,),(('ushighways',),),),
             ((6,(20,20,20,96),1,),(('interstates',),),),
             ((6,(20,20,20,96),1,),(('otherroutes',),),),
             ((1,(20,20,20,255),2,),(('counties',),),),
             ((2,(20,20,20,255),2,),(('states',),),),
             ((1,(20,20,20,255),2,),(('coastlines',),),),
             ((3,(130,130,130,255),2,),(('statehighways',),),),
             ((3,(130,130,130,255),2,),(('ushighways',),),),
             ((3,(130,130,130,255),2,),(('interstates',),),),
             ((3,(130,130,130,255),2,),(('otherroutes',),),),
             ],
)
dsm.set('Config.1.Radar_LocalDoppler', d, 0)
#
# Local_MetroDopplerRadar (MAP DATA)
d = twc.Data(mapName='mercator.us.bfg',
             mapcutCoordinate={metro_doppler_cut},
             mapcutSize=(1440,960),
             mapFinalSize=(720,480),
             mapMilesSize=(134,107),
             datacutType='radar.us',
             datacutCoordinate={metro_doppler_datacut},
             datacutSize=(177,118),
             dataFinalSize=(720,480),
             dataOffset=(0,0),
             vectors=['mercator.us.ushighways.vg','mercator.us.counties.vg','mercator.us.states.vg','mercator.us.coastlines.vg','mercator.us.statehighways.vg','mercator.us.otherroutes.vg','mercator.us.interstates.vg',],
)
wxdata.setMapData('Config.1.Local_MetroDopplerRadar', d, 0)
#
d = twc.Data(
  tiffImage = [
             (('locatorDotOutline',0,2,1,),(((360,240),),),),
             (('locatorDot',0,1,0,),(((360,240),),),),
        ],
  textString = [
             (('Interstate-Black',32,(255,255,255,204),1,0,0,(20,20,20,68),1,0,0,),(((260,290),'{loc_name.upper()}',),),),
             (('Interstate-Black',32,(255,255,255,255),1,0,0,(20,20,20,68),2,0,0,),(((260,290),'{loc_name.upper()}',),),),
        ],
  vector = [
             ((8,(20,20,20,96),1,),(('statehighways',),),),
             ((8,(20,20,20,96),1,),(('ushighways',),),),
             ((8,(20,20,20,96),1,),(('interstates',),),),
             ((8,(20,20,20,96),1,),(('otherroutes',),),),
             ((2,(20,20,20,255),2,),(('counties',),),),
             ((4,(20,20,20,255),2,),(('states',),),),
             ((2,(20,20,20,255),2,),(('coastlines',),),),
             ((4,(130,130,130,255),2,),(('statehighways',),),),
             ((4,(130,130,130,255),2,),(('ushighways',),),),
             ((4,(130,130,130,255),2,),(('interstates',),),),
             ((4,(130,130,130,255),2,),(('otherroutes',),),),
             ],
)
dsm.set('Config.1.Local_MetroDopplerRadar', d, 0)
#
# Local_RegionalDopplerRadar (MAP DATA)
d = twc.Data(mapName='mercator.us.bfg',
             mapcutCoordinate={regional_doppler_cut},
             mapcutSize=(2880,1644),
             mapFinalSize=(720,411),
             mapMilesSize=(268,184),
             datacutType='radar.us',
             datacutCoordinate={regional_doppler_datacut},
             datacutSize=(352,201),
             dataFinalSize=(720,411),
             dataOffset=(0,0),
             vectors=['mercator.us.ushighways.vg','mercator.us.counties.vg','mercator.us.states.vg','mercator.us.coastlines.vg','mercator.us.statehighways.vg','mercator.us.interstates.vg',],
)
wxdata.setMapData('Config.1.Local_RegionalDopplerRadar', d, 0)
#
d = twc.Data(
  tiffImage = [
             (('locatorDotOutline',0,2,1,),(((360,206),),),),
             (('locatorDot',0,1,0,),(((360,206),),),),
        ],
  textString = [
             (('Interstate-Black',32,(255,255,255,204),1,0,0,(20,20,20,68),1,0,0,),(((260,260),'{loc_name.upper()}',),),),
             (('Interstate-Black',32,(255,255,255,255),1,0,0,(20,20,20,68),2,0,0,),(((260,260),'{loc_name.upper()}',),),),
        ],
  vector = [
             ((2,(20,20,20,255),2,),(('counties',),),),
             ((4,(20,20,20,255),2,),(('states',),),),
             ((2,(20,20,20,255),2,),(('coastlines',),),),
             ((4,(130,130,130,255),2,),(('statehighways',),),),
             ((4,(130,130,130,255),2,),(('ushighways',),),),
             ((4,(130,130,130,255),2,),(('interstates',),),),
             ],
)
dsm.set('Config.1.Local_RegionalDopplerRadar', d, 0)
#
# Local_RadarSatelliteComposite (MAP DATA)
d = twc.Data(mapName='lambert.us.tif',
             mapcutCoordinate={radar_sat_cut},
             mapcutSize=(936,624),
             mapFinalSize=(720,480),
             mapMilesSize=(879,590),
             datacutType='radarSatellite.us',
             datacutCoordinate={radar_sat_datacut},
             datacutSize=(481,322),
             dataFinalSize=(720,480),
             dataOffset=(0,0),
             vectors=['lambert.us.coastlines.vg','lambert.us.states.vg',],
)
wxdata.setMapData('Config.1.Local_RadarSatelliteComposite', d, 0)
#
d = twc.Data(
  tiffImage = [
             (('locatorDotOutline',0,2,1,),(((360,240),),),),
             (('locatorDot',0,1,0,),(((360,240),),),),
        ],
  textString = [
             (('Interstate-Black',32,(255,255,255,204),1,0,0,(20,20,20,68),1,0,0,),(((260,290),'{loc_name.upper()}',),),),
             (('Interstate-Black',32,(255,255,255,255),1,0,0,(20,20,20,68),2,0,0,),(((260,290),'{loc_name.upper()}',),),),
        ],
  vector = [
             ((2,(20,20,20,255),2,),(('states',),),),
             ((1,(20,20,20,255),2,),(('coastlines',),),),
             ],
)
dsm.set('Config.1.Local_RadarSatelliteComposite', d, 0)
#
# NationalLdl_RadarSatellite (MAP DATA)
d = twc.Data(mapName='lambert.us.tif',
             mapcutCoordinate={nldl_satellite_cut},
             mapcutSize=(1072,611),
             mapFinalSize=(193,110),
             mapMilesSize=(1006,578),
             datacutType='radarSatellite.us',
             datacutCoordinate={nldl_satellite_datacut},
             datacutSize=(551,315),
             dataFinalSize=(193,110),
             dataOffset=(0,0),
             vectors=['lambert.us.coastlines.vg','lambert.us.states.vg',],
)
wxdata.setMapData('Config.1.NationalLdl_RadarSatellite', d, 0)
#
d = twc.Data(
  vector = [
             ((2,(20,20,20,255),2,),(('states',),),),
             ((2,(20,20,20,255),2,),(('coastlines',),),),
             ],
)
dsm.set('Config.1.NationalLdl_RadarSatellite', d, 0)
#
# Local_MetroObservationMap (MAP DATA)
d = twc.Data(mapName='mercator.us.bfg',
             mapcutCoordinate={metro_obs_cut},
             mapcutSize=(1584,1056),
             mapFinalSize=(720,480),
             mapMilesSize=(147,117),
             vectors=['mercator.us.ushighways.vg','mercator.us.counties.vg','mercator.us.states.vg','mercator.us.coastlines.vg','mercator.us.statehighways.vg','mercator.us.otherroutes.vg','mercator.us.interstates.vg',],
)
wxdata.setMapData('Config.1.Local_MetroObservationMap', d, 0)
#
d = twc.Data(
  labeledTiffImage = [],
  obsValue = [],
  obsIcon = [],
  textString = [],
  vector = [
             ((8,(20,20,20,96),1,),(('statehighways',),),),
             ((8,(20,20,20,96),1,),(('ushighways',),),),
             ((8,(20,20,20,96),1,),(('interstates',),),),
             ((8,(20,20,20,96),1,),(('otherroutes',),),),
             ((2,(20,20,20,255),1,),(('counties',),),),
             ((4,(20,20,20,255),1,),(('states',),),),
             ((2,(20,20,20,255),1,),(('coastlines',),),),
             ((4,(130,130,130,255),1,),(('statehighways',),),),
             ((4,(130,130,130,255),1,),(('ushighways',),),),
             ((4,(130,130,130,255),1,),(('interstates',),),),
             ((4,(130,130,130,255),1,),(('otherroutes',),),),
             ],
)
dsm.set('Config.1.Local_MetroObservationMap', d, 0)
#
# Local_MetroForecastMap (MAP DATA)
d = twc.Data(mapName='mercator.us.bfg',
             mapcutCoordinate={metro_fcst_cut},
             mapcutSize=(1584,1056),
             mapFinalSize=(720,480),
             mapMilesSize=(147,117),
             vectors=['mercator.us.ushighways.vg','mercator.us.counties.vg','mercator.us.states.vg','mercator.us.coastlines.vg','mercator.us.statehighways.vg','mercator.us.otherroutes.vg','mercator.us.interstates.vg',],
)
wxdata.setMapData('Config.1.Local_MetroForecastMap', d, 0)
#
d = twc.Data(
  labeledTiffImage = [],
  fcstValue = [],
  fcstIcon = [],
  textString = [],
  vector = [
             ((8,(20,20,20,96),1,),(('statehighways',),),),
             ((8,(20,20,20,96),1,),(('ushighways',),),),
             ((8,(20,20,20,96),1,),(('interstates',),),),
             ((8,(20,20,20,96),1,),(('otherroutes',),),),
             ((2,(20,20,20,255),1,),(('counties',),),),
             ((4,(20,20,20,255),1,),(('states',),),),
             ((2,(20,20,20,255),1,),(('coastlines',),),),
             ((4,(130,130,130,255),1,),(('statehighways',),),),
             ((4,(130,130,130,255),1,),(('ushighways',),),),
             ((4,(130,130,130,255),1,),(('interstates',),),),
             ((4,(130,130,130,255),1,),(('otherroutes',),),),
             ],
)
dsm.set('Config.1.Local_MetroForecastMap', d, 0)
#
# Local_RegionalObservationMap (MAP DATA)
d = twc.Data(mapName='mercator.us.bfg',
             mapcutCoordinate={regional_obs_cut},
             mapcutSize=(5760,3840),
             mapFinalSize=(720,480),
             mapMilesSize=(535,428),
             vectors=['mercator.us.ushighways.vg','mercator.us.counties.vg','mercator.us.states.vg','mercator.us.coastlines.vg','mercator.us.statehighways.vg','mercator.us.interstates.vg',],
)
wxdata.setMapData('Config.1.Local_RegionalObservationMap', d, 0)
#
d = twc.Data(
  labeledTiffImage = [],
  obsValue = [],
  obsIcon = [],
  textString = [],
  vector = [
             ((2,(20,20,20,255),2,),(('counties',),),),
             ((4,(20,20,20,255),2,),(('states',),),),
             ((2,(20,20,20,255),2,),(('coastlines',),),),
             ((4,(130,130,130,255),2,),(('statehighways',),),),
             ((4,(130,130,130,255),2,),(('ushighways',),),),
             ((4,(130,130,130,255),2,),(('interstates',),),),
             ],
)
dsm.set('Config.1.Local_RegionalObservationMap', d, 0)
#
# Local_RegionalForecastMap (MAP DATA)
d = twc.Data(mapName='mercator.us.bfg',
             mapcutCoordinate={regional_fcst_cut},
             mapcutSize=(5760,3840),
             mapFinalSize=(720,480),
             mapMilesSize=(535,428),
             vectors=['mercator.us.ushighways.vg','mercator.us.counties.vg','mercator.us.states.vg','mercator.us.coastlines.vg','mercator.us.statehighways.vg','mercator.us.interstates.vg',],
)
wxdata.setMapData('Config.1.Local_RegionalForecastMap', d, 0)
#
d = twc.Data(
  labeledTiffImage = [],
  fcstValue = [],
  fcstIcon = [],
  textString = [],
  vector = [
             ((2,(20,20,20,255),2,),(('counties',),),),
             ((4,(20,20,20,255),2,),(('states',),),),
             ((2,(20,20,20,255),2,),(('coastlines',),),),
             ((4,(130,130,130,255),2,),(('statehighways',),),),
             ((4,(130,130,130,255),2,),(('ushighways',),),),
             ((4,(130,130,130,255),2,),(('interstates',),),),
             ],
)
dsm.set('Config.1.Local_RegionalForecastMap', d, 0)
#
# Local_Satellite (MAP DATA)
d = twc.Data(mapName='lambert.us.tif',
             mapcutCoordinate={satellite_cut},
             mapcutSize=(2196,1464),
             mapFinalSize=(720,480),
             mapMilesSize=(2006,1349),
             datacutType='satellite.us',
             datacutCoordinate={satellite_datacut},
             datacutSize=(590,394),
             dataFinalSize=(720,480),
             dataOffset=(0,0),
             vectors=['lambert.us.coastlines.vg','lambert.us.states.vg',],
)
wxdata.setMapData('Config.1.Local_Satellite', d, 0)
#
d = twc.Data(
  tiffImage = [
             (('locatorDot',0,2,0,),(((360,240),),),),
        ],
  textString = [],
  vector = [
             ((2,(20,20,20,255),2,),(('states',),),),
             ((2,(20,20,20,255),2,),(('coastlines',),),),
             ],
)
dsm.set('Config.1.Local_Satellite', d, 0)
#
"""


def compile_interest_list(config: "AggregatedConfig") -> str:
    return f"""#
# DATA INTEREST LISTS
#
wxdata.setInterestList('airportId','1',[{quote_list(config.airport_ids) if config.airport_ids else ''}])
wxdata.setInterestList('coopId','1',[{quote_list(config.coop_ids)}])
wxdata.setInterestList('indexId','1',['{config.airport_ids[0] if config.airport_ids else ""}',])
wxdata.setInterestList('pollenId','1',['{config.airport_ids[0] if config.airport_ids else ""}',])
wxdata.setInterestList('obsStation','1',[{quote_list(config.tecci_ids + config.obs_stations)}])
wxdata.setInterestList('climId','1',[{quote_list(config.climate_ids)}])
wxdata.setInterestList('metroId','1',[])
wxdata.setInterestList('zone','1',[{quote_list(config.zone_ids)}])
wxdata.setInterestList('aq','1',['zz001',])
wxdata.setInterestList('zone.cwf','1',[])
wxdata.setInterestList('tideStation','1',[])
wxdata.setInterestList('skiId','1',[])
wxdata.setInterestList('county','1',[{quote_list(config.county_ids)}])
"""


def compile_metadata(config: "AggregatedConfig", random_cable_name: str, random_star_id: int, timezone: str) -> str:
    county_list = [(cid, cname) for cid, cname in config.county_names.items()]
    county_list_str = str(county_list) if county_list else "[]"

    return f"""#
# SYSTEM METADATA
#
dsm.set('Config.1.countyNameList',{county_list_str}, 0)
#
dsm.set('dmaCode','000', 0)
dsm.set('secondaryObsStation','{config.tecci_ids[1] if len(config.tecci_ids) > 1 else config.tecci_ids[0] if config.tecci_ids else ""}', 0)
dsm.set('primaryClimoStation','{config.climate_ids[0] if config.climate_ids else ""}', 0)
dsm.set('primaryIndexId','{config.airport_ids[0] if config.airport_ids else ""}', 0)
dsm.set('ThemeOverride','standard', 0)
dsm.set('stateCode','{config.state_code}', 0)
dsm.set('primaryAqStation','zz001', 0)
dsm.set('primPollenSiteName','{config.name}', 0)
dsm.set('expRev','0000000', 0)
dsm.set('primaryCoopId','{config.coop_ids[0] if config.coop_ids else ""}', 0)
dsm.set('Config.1.PlaylistOverride','DefaultUS', 0)
dsm.set('wda','{config.airport_ids[0] if config.airport_ids else ""}', 0)
dsm.set('primaryCounty','{config.county_ids[0] if config.county_ids else ""}', 0)
dsm.set('primaryObsStation','{config.tecci_ids[0] if config.tecci_ids else ""}', 0)
dsm.set('primaryLat',{config.lat}, 0)
dsm.set('hasTraffic',0, 0)
dsm.set('primaryPollenStation','{config.airport_ids[0] if config.airport_ids else ""}', 0)
dsm.set('Config.1.Clock','scmt.clock', 0)
dsm.set('primaryLon',{config.lon}, 0)
dsm.set('primaryForecastName','{config.name}', 0)
dsm.set('primaryZone','{config.zone_ids[0] if config.zone_ids else ""}', 0)
dsm.set('climoRegion','3', 0)
dsm.set('Config.1.SevereClock','scmt_severe.clock', 0)
dsm.set('onAirName','{random_cable_name},', 0)
dsm.set('headendId','{random_star_id:06d}', 0)
dsm.set('msoName','{random_cable_name}', 0)
dsm.set('countryCode','{config.country_code}', 0)
dsm.set('cableSystemName','{random_cable_name},', 0)
dsm.set('msoCode','00000', 0)
dsm.set('headendName','DOM - {config.name.upper()} - DOM', 0)
dsm.set('affiliateNumber','00000', 0)
dsm.set('zipCode','00000', 0)
dsm.set('Config.1.irdAddress','0000000000000000', 0)
dsm.set('Config.1.starId','TWCD00000000', 0)
dsm.set('Config.1.irdSlave','0', 0)
#
wxdata.setTimeZone('{timezone}')
#
"""


def compile_override_block() -> str:
    return """# BLOCK BEGIN
d = twc.Data()
dsm.set('Config.1.Override', d, 0)
d = twc.Data()
d.activeVocal = 1
dsm.set('Config.1.Bulletin_Default', d, 0)
# BLOCK END
#
d = twc.Data()
d.sponsorLogo = ''
dsm.set('Config.1', d, 0, 1)
#
"""


def compile_airport_data(config: "AggregatedConfig", all_records: list["LocationRecord"]) -> str:
    airport_records = [r for r in all_records if r.airport_id][:3]
    
    if not airport_records:
        return ""
    
    airport_ids = [r.airport_id for r in airport_records]
    airport_names = [r.name for r in airport_records]
    airport_teccis = [r.teccis[0] if r.teccis else r.obs_station for r in airport_records]
    
    return f"""scmtRemove('Config.1.Tag.General.airportData')
d = twc.Data()
d.airportId = [{quote_list(airport_ids)}]
d.airportLocName = [{quote_list(airport_names)}]
d.obsStation = [{quote_list(airport_teccis)}]
dsm.set('Config.1.Tag.General.airportData', d, 0, 1)
#
"""


def compile_snowboard_data() -> str:
    return """scmtRemove('Config.1.Tag.General.snowboardData')
d = twc.Data()
d.permCode = []
d.coopId = []
d.resortName = []
dsm.set('Config.1.Tag.General.snowboardData', d, 0, 1)
#
"""


def compile_non_image_maps() -> str:
    return """#
#  Non Image Maps
#
d = [
'Config.1.Local_MetroForecastMap',
'Config.1.Local_MetroObservationMap',
'Config.1.Local_RegionalForecastMap',
'Config.1.Local_RegionalObservationMap',
]
dsm.set('Config.1.nonImageMaps', d, 0)
#
"""


def compile_vocal_schedule() -> str:
    return """scmtRemove('Config.1.VocalLocalSchedule')
d = twc.Data()
d.OffTimes = ( )
dsm.set('Config.1.VocalLocalSchedule', d, 0, 1)
#
scmtRemove('Config.1.Ldl_LASCrawl')
scmtRemove('Config.1.LASCrawl')
#
"""


def compile_scmt_removes() -> str:
    domestic_products = [
        'Config.1.NationalLdl_5DayForecastSmall.2',
        'Config.1.Ldl_HurricaneWatch',
        'Config.1.Local_NWSHeadlines',
        'Config.1.NationalLdl_5DayForecast.4',
        'Config.1.NationalLdl_5DayForecast.1',
        'Config.1.TimeTemp_Default',
        'Config.1.NationalLdl_WeatherBulletin.0',
        'Config.1.NationalLdl_CurrentConditions.2',
        'Config.1.Local_SchoolDayWeather',
        'Config.1.Ldl_3DayForecast',
        'Config.1.Local_AirQualityForecast',
        'Config.1.Local_Tides',
        'Config.1.Local_GetawayForecast',
        'Config.1.NationalLdl_CurrentConditionsSmall.3',
        'Config.1.Local_Almanac',
        'Config.1.NationalLdl_CurrentConditionsSmall.0',
        'Config.1.Local_RecordHighLow',
        'Config.1.NationalLdl_CurrentConditionsSmall.5',
        'Config.1.Ldl_CurrentObs.1',
        'Config.1.Local_Climatology',
        'Config.1.NationalLdl_5DayForecastSmall.1',
        'Config.1.Fcst_ExtendedForecast',
        'Config.1.Local_TrafficOverview',
        'Config.1.NationalLdl_5DayForecastSmall.5',
        'Config.1.Local_MarineForecast',
        'Config.1.Fcst_DaypartForecast',
        'Config.1.Ldl_CurrentObs.3',
        'Config.1.NationalLdl_CurrentConditions.5',
        'Config.1.Ldl_AirportDelayConditions',
        'Config.1.NationalLdl_CurrentConditionsSmall.2',
        'Config.1.Ldl_TrafficTripTimes',
        'Config.1.NationalLdl_5DayForecast.2',
        'Config.1.Local_TextForecast',
        'Config.1.Ldl_CurrentObs.0',
        'Config.1.NationalLdl_CurrentConditions.1',
        'Config.1.Local_LocalObservations',
        'Config.1.Local_HeatSafetyTips',
        'Config.1.NationalLdl_5DayForecastSmall.0',
        'Config.1.Ldl_StarIDMessage',
        'Config.1.NationalLdl_5DayForecast.5',
        'Config.1.NationalLdl_5DayForecastSmall.3',
        'Config.1.NationalLdl_CurrentConditions.4',
        'Config.1.Local_CurrentConditions',
        'Config.1.Ldl_CurrentObs.2',
        'Config.1.NationalLdl_CurrentConditions.0',
        'Config.1.NationalLdl_CurrentConditionsSmall.1',
        'Config.1.Ldl_HourlyForecast',
        'Config.1.Local_ExtendedForecast',
        'Config.1.Local_7DayForecast',
        'Config.1.Cc_CurrentConditions',
        'Config.1.NationalLdl_5DayForecast.0',
        'Config.1.Local_TrafficFlow',
        'Config.1.Ldl_Almanac',
        'Config.1.Ldl_UVForecast',
        'Config.1.Local_TrafficReport',
        'Config.1.Ldl_Almanac.1',
        'Config.1.Ldl_DailyForecast.1',
        'Config.1.Local_OutdoorActivityForecast',
        'Config.1.NationalLdl_5DayForecast.3',
        'Config.1.Ldl_AirQualityForecast',
        'Config.1.Ldl_TravelForecast',
        'Config.1.NationalLdl_CurrentConditionsSmall.4',
        'Config.1.NationalLdl_5DayForecastSmall.4',
        'Config.1.Local_EventForecast',
        'Config.1.Local_DaypartForecast',
        'Config.1.NationalLdl_CurrentConditions.3',
        'Config.1.Fcst_TextForecast',
        'Config.1.Ldl_DailyForecast',
    ]
    
    lines = ["#"]
    lines.extend([f"scmtRemove('{product}')" for product in domestic_products])
    lines.append("#")
    return "\n".join(lines)

def compile_heat_safety(config: "AggregatedConfig") -> str:
    obs_station = config.tecci_ids[0] if config.tecci_ids else ""
    return f"""d = twc.Data()
d.obsStation = '{obs_station}'
d.locName = '{config.name.upper()}'
d.heatIndexThreshold = 100
dsm.set('Config.1.Local_HeatSafetyTips', d, 0, 1)
#
"""

def compile_uv_forecast(config: "AggregatedConfig") -> str:
    coop_id = config.coop_ids[0] if config.coop_ids else ""
    return f"""d = twc.Data()
d.locName = '{config.name}'
d.startDate = (5,1)
d.endDate = (9,30)
d.coopId = '{coop_id}'
d.prodLabel = 'UV Index'
dsm.set('Config.1.Ldl_UVForecast', d, 0, 1)
#
"""

def compile_daily_forecast(config: "AggregatedConfig", all_records: list["LocationRecord"]) -> str:
    loc_names = [config.name]
    coop_ids = [config.coop_ids[0]] if config.coop_ids else []
    
    for record in all_records[1:3]:
        if record.name and record.coop_id:
            loc_names.append(record.name)
            coop_ids.append(record.coop_id)
    
    return f"""d = twc.Data()
d.dayOfs = 1
d.locName = [{quote_list(loc_names)}]
d.coopId = [{quote_list(coop_ids)}]
dsm.set('Config.1.Ldl_DailyForecast.1', d, 0, 1)
#
d = twc.Data()
d.dayOfs = 0
d.locName = [{quote_list(loc_names)}]
d.coopId = [{quote_list(coop_ids)}]
dsm.set('Config.1.Ldl_DailyForecast', d, 0, 1)
#
"""


def compile_national_ldl_products(config: "AggregatedConfig", all_records: list["LocationRecord"]) -> str:
    primary_obs = config.tecci_ids[0] if config.tecci_ids else ""
    primary_name = config.name
    primary_coop = config.coop_ids[0] if config.coop_ids else ""
    
    secondary_records = [r for r in all_records[1:3] if r.coop_id]
    
    lines: list[str] = []
    
    lines.append(f"""d = twc.Data()
d.obsStation = ['{primary_obs}',]
d.locName = ['{primary_name}',]
d.coopId = ['{primary_coop}',]
dsm.set('Config.1.NationalLdl_5DayForecast.0', d, 0, 1)
#
ds.commit()
dsm.set('Config.1.NationalLdl_36HourForecast.0', d, 0, 1)
dsm.set('Config.1.NationalLdl_DaypartForecast.0', d, 0, 1)
dsm.set('Config.1.NationalLdl_HourlyForecast.0', d, 0, 1)
dsm.set('Config.1.NationalLdl_TextForecast.0', d, 0, 1)
#""")
    
    lines.append(f"""d = twc.Data()
d.obsStation = ['{primary_obs}',]
d.locName = ['{primary_name}',]
dsm.set('Config.1.NationalLdl_CurrentConditions.0', d, 0, 1)
#
d = twc.Data()
d.obsStation = ['{primary_obs}',]
d.locName = ['{primary_name}',]
dsm.set('Config.1.NationalLdl_CurrentConditionsSmall.0', d, 0, 1)
#
d = twc.Data()
d.obsStation = ['{primary_obs}',]
d.locName = ['{primary_name}',]
d.coopId = ['{primary_coop}',]
dsm.set('Config.1.NationalLdl_5DayForecastSmall.0', d, 0, 1)
#
ds.commit()
dsm.set('Config.1.NationalLdl_DaypartForecastSmall.0', d, 0, 1)
#""")
    
    for i, record in enumerate(secondary_records[:2], start=1):
        tecci = record.teccis[0] if record.teccis else record.obs_station or ""
        lines.append(f"""d = twc.Data()
d.obsStation = ['{tecci}',]
d.locName = ['{record.name}',]
d.coopId = ['{record.coop_id}',]
dsm.set('Config.1.NationalLdl_5DayForecast.{i}', d, 0, 1)
#
ds.commit()
dsm.set('Config.1.NationalLdl_36HourForecast.{i}', d, 0, 1)
dsm.set('Config.1.NationalLdl_HourlyForecast.{i}', d, 0, 1)
#
d = twc.Data()
d.obsStation = ['{tecci}',]
d.locName = ['{record.name}',]
dsm.set('Config.1.NationalLdl_CurrentConditions.{i}', d, 0, 1)
#
d = twc.Data()
d.obsStation = ['{tecci}',]
d.locName = ['{record.name}',]
dsm.set('Config.1.NationalLdl_CurrentConditionsSmall.{i}', d, 0, 1)
#
d = twc.Data()
d.obsStation = ['{tecci}',]
d.locName = ['{record.name}',]
d.coopId = ['{record.coop_id}',]
dsm.set('Config.1.NationalLdl_5DayForecastSmall.{i}', d, 0, 1)
#
ds.commit()
dsm.set('Config.1.NationalLdl_DaypartForecastSmall.{i}', d, 0, 1)
#""")
    
    lines.append(f"""d = twc.Data()
d.obsStation = ['{primary_obs}',]
d.locName = ['{primary_name.upper()}',]
dsm.set('Config.1.NationalLdl_RadarSatellite', d, 0, 1)
#
d = twc.Data()
d.obsStation = ['{primary_obs}',]
d.locName = ['{primary_name.upper()}',]
dsm.set('Config.1.NationalLdl_DopplerRadar', d, 0, 1)
#""")
    
    return "\n".join(lines)


def compile_local_daypart_forecast(config: "AggregatedConfig") -> str:
    coop_id = config.coop_ids[0] if config.coop_ids else ""
    return f"""d = twc.Data()
d.locName = ['{config.name.upper()}',]
d.coopId = ['{coop_id}',]
dsm.set('Config.1.Local_DaypartForecast', d, 0, 1)
#
"""


def compile_nws_headlines(config: "AggregatedConfig") -> str:
    zone = config.zone_ids[0] if config.zone_ids else ""
    return f"""d = twc.Data()
d.zone = '{zone}'
d.activeVocalCue = 1
d.activeVocal = 1
dsm.set('Config.1.Local_NWSHeadlines', d, 0, 1)
#
"""


def compile_ldl_current_obs(config: "AggregatedConfig", all_records: list["LocationRecord"]) -> str:
    obs_stations: list[str] = []
    loc_names: list[str] = []
    
    for record in all_records[:3]:
        tecci = record.teccis[0] if record.teccis else record.obs_station
        if tecci:
            obs_stations.append(tecci)
            loc_names.append(record.name)
    
    if not obs_stations:
        return ""
    
    return f"""d = twc.Data()
d.obsStation = [{quote_list(obs_stations[:2])}]
d.dataTypes = ['SkyTemp', 'Winds', 'Gusts', 'Humidity', 'ApparentTemp']
d.prodLabel = 'Now'
d.obsLocName = [{quote_list(loc_names[:2] if len(loc_names) > 0 else [])}]
d.primaryObsProduct = 1
dsm.set('Config.1.Ldl_CurrentObs.0', d, 0, 1)
#
d = twc.Data()
d.obsStation = ['{obs_stations[1] if len(obs_stations) > 1 else obs_stations[0]}',]
d.dataTypes = ['SkyTemp']
d.prodLabel = 'Now'
d.obsLocName = ['{loc_names[1] if len(loc_names) > 1 else loc_names[0]}',]
d.primaryObsProduct = 0
dsm.set('Config.1.Ldl_CurrentObs.1', d, 0, 1)
#
d = twc.Data()
d.obsStation = ['{obs_stations[2] if len(obs_stations) > 2 else obs_stations[0]}',]
d.dataTypes = ['SkyTemp']
d.prodLabel = 'Now'
d.obsLocName = ['{loc_names[2] if len(loc_names) > 2 else loc_names[0]}',]
d.primaryObsProduct = 0
dsm.set('Config.1.Ldl_CurrentObs.2', d, 0, 1)
#
d = twc.Data()
d.obsStation = [{quote_list(obs_stations[:2])}]
d.dataTypes = ['StarId', 'SkyTemp', 'Winds', 'Gusts', 'Humidity', 'ApparentTemp', 'Dewpoint', 'Pressure', 'Ceiling', 'Visibility', 'MTDPrecip']
d.prodLabel = 'Now'
d.obsLocName = [{quote_list(loc_names[:2] if len(loc_names) > 0 else [])}]
d.primaryObsProduct = 1
dsm.set('Config.1.Ldl_CurrentObs.3', d, 0, 1)
#
"""


def compile_weather_bulletin(config: "AggregatedConfig") -> str:
    obs_station = config.tecci_ids[0] if config.tecci_ids else ""
    zone = config.zone_ids[0] if config.zone_ids else ""
    return f"""d = twc.Data()
d.obsStation = ['{obs_station}',]
d.locName = ['{config.name}',]
d.zone = '{zone}'
dsm.set('Config.1.NationalLdl_WeatherBulletin.0', d, 0, 1)
#
"""


def compile_outdoor_activity(config: "AggregatedConfig") -> str:
    coop_id = config.coop_ids[0] if config.coop_ids else ""
    return f"""d = twc.Data()
d.coopId = '{coop_id}'
dsm.set('Config.1.Local_OutdoorActivityForecast', d, 0, 1)
#
"""


def compile_extended_forecast(config: "AggregatedConfig") -> str:
    coop_id = config.coop_ids[0] if config.coop_ids else ""
    return f"""d = twc.Data()
d.location = '{config.name.upper()}'
d.coopId = '{coop_id}'
d.activeVocalCue = 1
d.activeVocal = 1
dsm.set('Config.1.Local_ExtendedForecast', d, 0, 1)
#
"""


def compile_hourly_forecast(config: "AggregatedConfig") -> str:
    coop_id = config.coop_ids[0] if config.coop_ids else ""
    return f"""d = twc.Data()
d.locName = '{config.name}'
d.hrsGrid = (((0, 4), 6, 12, 18), ((4, 8), 9, 12, 18), ((8, 11), 12, 15, 18), ((11, 14), 15, 18, 21), ((14, 17), 18, 21, 24), ((17, 20), 21, 24, 30), ((20, 24), 30, 36, 42),)
d.coopId = '{coop_id}'
dsm.set('Config.1.Ldl_HourlyForecast', d, 0, 1)
#
"""


def compile_7day_forecast(config: "AggregatedConfig") -> str:
    coop_id = config.coop_ids[0] if config.coop_ids else ""
    return f"""d = twc.Data()
d.locName = '{config.name.upper()}'
d.coopId = '{coop_id}'
d.activeVocalCue = 1
dsm.set('Config.1.Local_7DayForecast', d, 0, 1)
#
"""


def compile_school_day_weather(config: "AggregatedConfig") -> str:
    obs_stations = config.tecci_ids[:2] if config.tecci_ids else []
    coop_id = config.coop_ids[0] if config.coop_ids else ""
    return f"""d = twc.Data()
d.obsStation = [{quote_list(obs_stations)}]
d.schedule = [((11,20,16,0,0), (11,23,16,0,0)),((12,16,16,0,0), (1,4,16,0,0)),((5,25,16,0,0), (9,1,16,0,0)),]
d.coopId = '{coop_id}'
dsm.set('Config.1.Local_SchoolDayWeather', d, 0, 1)
#
"""


def compile_airport_delays(config: "AggregatedConfig", all_records: list["LocationRecord"]) -> str:
    airport_records = [r for r in all_records if r.airport_id][:1]
    
    if not airport_records:
        return ""
    
    record = airport_records[0]
    airport_id = record.airport_id
    tecci = record.teccis[0] if record.teccis else record.obs_station
    
    return f"""d = twc.Data()
d.airportId = ['{airport_id}',]
d.obsStation = ['{tecci}',]
d.locName = ['{record.name} Int\\'l',]
d.displayFlag = [1,]
d.prodLabel = 'Airport'
dsm.set('Config.1.Ldl_AirportDelayConditions', d, 0, 1)
#
"""


def compile_getaway_forecast(config: "AggregatedConfig", all_records: list["LocationRecord"]) -> str:
    getaway_records = all_records[1:4]
    
    if not getaway_records:
        return ""
    
    loc_names = [r.name + ", " + r.state_code for r in getaway_records if r.state_code]
    coop_ids = [r.coop_id for r in getaway_records if r.coop_id]
    
    if not coop_ids:
        return ""
    
    return f"""d = twc.Data()
d.url = [{quote_list([''] * len(loc_names))}]
d.locNameList = [{quote_list(loc_names[:len(coop_ids)])}]
d.coopId = [{quote_list(coop_ids)}]
dsm.set('Config.1.Local_GetawayForecast', d, 0, 1)
#
"""


def compile_air_quality(config: "AggregatedConfig") -> str:
    return f"""d = twc.Data()
d.locName = '{config.state_code}'
d.startDate = (1,1)
d.endDate = (12,31)
d.prodLabel = 'Air Quality'
d.aq = 'zz001'
dsm.set('Config.1.Ldl_AirQualityForecast', d, 0, 1)
#
d = twc.Data()
d.locName = ['{config.state_code}',]
d.actionDayPhrase = 'Air Quality Action Day'
d.aq = ['zz001',]
dsm.set('Config.1.Local_AirQualityForecast', d, 0, 1)
#
"""


def compile_text_forecast(config: "AggregatedConfig") -> str:
    coop_id = config.coop_ids[0] if config.coop_ids else ""
    return f"""d = twc.Data()
d.minPageDuration = 8
d.locName = '{config.name.upper()}'
d.coopId = '{coop_id}'
d.maxPageDuration = 14
d.activeVocalCue = 1
d.activeVocal = 1
dsm.set('Config.1.Local_TextForecast', d, 0, 1)
#
"""


def compile_time_temp(config: "AggregatedConfig") -> str:
    obs_stations = config.tecci_ids[:3] if config.tecci_ids else []
    return f"""d = twc.Data()
d.obsStation = [{quote_list(obs_stations[:2])}]
d.timeDuration = 5
d.tempDuration = 8
dsm.set('Config.1.TimeTemp_Default', d, 0, 1)
#
"""


def compile_current_conditions(config: "AggregatedConfig") -> str:
    obs_stations = config.tecci_ids[:3] if config.tecci_ids else []
    loc_names = [config.name.upper()] * min(3, len(obs_stations) + 1)
    
    return f"""d = twc.Data()
d.obsStation = [{quote_list(obs_stations[:2])}]
d.locName = [{quote_list(loc_names[:len(obs_stations)+1])}]
d.activeVocalCue = 1
d.activeVocal = 1
dsm.set('Config.1.Local_CurrentConditions', d, 0, 1)
#
"""


def compile_local_observations(config: "AggregatedConfig", all_records: list["LocationRecord"]) -> str:
    obs_stations: list[str] = []
    loc_names: list[str] = []
    
    for record in all_records[1:9]:
        tecci = record.teccis[0] if record.teccis else record.obs_station
        if tecci:
            obs_stations.append(tecci)
            loc_names.append(record.name)
    
    if not obs_stations:
        return ""
    
    return f"""d = twc.Data()
d.obsStation = [{quote_list(obs_stations)}]
d.locName = [{quote_list(loc_names)}]
dsm.set('Config.1.Local_LocalObservations', d, 0, 1)
#
"""


def compile_hurricane_watch() -> str:
    return """d = twc.Data()
d.crawlRate = 3
dsm.set('Config.1.Ldl_HurricaneWatch', d, 0, 1)
#
"""


def compile_climatology(config: "AggregatedConfig") -> str:
    obs_station = config.tecci_ids[0] if config.tecci_ids else ""
    clim_id = config.climate_ids[0] if config.climate_ids else ""
    coop_id = config.coop_ids[0] if config.coop_ids else ""
    return f"""d = twc.Data()
d.obsStation = '{obs_station}'
d.climId = '{clim_id}'
d.locName = '{config.name}'
d.coopId = '{coop_id}'
dsm.set('Config.1.Local_Climatology', d, 0, 1)
#
"""


def compile_record_high_low(config: "AggregatedConfig") -> str:
    obs_station = config.tecci_ids[0] if config.tecci_ids else ""
    clim_id = config.climate_ids[0] if config.climate_ids else ""
    coop_id = config.coop_ids[0] if config.coop_ids else ""
    return f"""d = twc.Data()
d.obsStation = '{obs_station}'
d.climId = '{clim_id}'
d.latitude = {config.lat}
d.longitude = {config.lon}
d.locName = '{config.name}'
d.coopId = '{coop_id}'
d.fcstHighOffset = 1
d.fcstLowOffset = 1
dsm.set('Config.1.Local_RecordHighLow', d, 0, 1)
#
"""


def compile_tides(config: "AggregatedConfig") -> str:
    return f"""d = twc.Data()
d.tideStation = ''
d.locName = '{config.name}'
dsm.set('Config.1.Local_Tides', d, 0, 1)
#
"""


def compile_marine_forecast(config: "AggregatedConfig") -> str:
    return f"""d = twc.Data()
d.locName = '{config.name}'
d.zone = ''
dsm.set('Config.1.Local_MarineForecast', d, 0, 1)
#
"""


def compile_event_forecast(config: "AggregatedConfig") -> str:
    coop_id = config.coop_ids[0] if config.coop_ids else ""
    return f"""d = twc.Data()
d.coopId = '{coop_id}'
d.locName = '{config.name}'
dsm.set('Config.1.Local_EventForecast', d, 0, 1)
#
"""


def compile_travel_forecast(config: "AggregatedConfig", all_records: list["LocationRecord"]) -> str:
    travel_records = [r for r in all_records[1:4] if r.coop_id]
    
    if not travel_records:
        return ""
    
    loc_names = [r.name for r in travel_records]
    coop_ids = [r.coop_id for r in travel_records]
    
    return f"""d = twc.Data()
d.dayOfs = 0
d.locName = [{quote_list(loc_names)}]
d.coopId = [{quote_list(coop_ids)}]
d.prodLabel = 'Travel'
dsm.set('Config.1.Ldl_TravelForecast', d, 0, 1)
#
"""


def compile_almanac(config: "AggregatedConfig") -> str:
    obs_station = config.tecci_ids[0] if config.tecci_ids else ""
    clim_id = config.climate_ids[0] if config.climate_ids else ""
    
    return f"""d = twc.Data()
d.obsStation = '{obs_station}'
d.climId = '{clim_id}'
d.latitude = {config.lat}
d.longitude = {config.lon}
d.dataTypes = ['Sunrise', 'MTDPrecip', 'HourlyRain', 'HourlySnow']
d.prodLabel = 'Almanac'
d.obsLocName = '{config.name}'
dsm.set('Config.1.Ldl_Almanac.1', d, 0, 1)
#
d = twc.Data()
d.obsStation = '{obs_station}'
d.climId = '{clim_id}'
d.latitude = {config.lat}
d.longitude = {config.lon}
d.dataTypes = ['Sunrise', 'AvgHiLo', 'MTDPrecip', 'HourlyRain', 'HourlySnow']
d.prodLabel = 'Almanac'
d.obsLocName = '{config.name}'
dsm.set('Config.1.Ldl_Almanac', d, 0, 1)
#
d = twc.Data()
d.climId = '{clim_id}'
d.latitude = {config.lat}
d.longitude = {config.lon}
dsm.set('Config.1.Local_Almanac', d, 0, 1)
#
"""


def compile_star_id_message() -> str:
    return """d = twc.Data()
d.displayMessage = 1
dsm.set('Config.1.Ldl_StarIDMessage', d, 0, 1)
#
"""


def compile_cc_current_conditions(config: "AggregatedConfig") -> str:
    obs_stations = config.tecci_ids[:2] if config.tecci_ids else []
    loc_names = [config.name] * min(2, len(obs_stations))
    
    return f"""d = twc.Data()
d.obsStation = [{quote_list(obs_stations)}]
d.locName = [{quote_list(loc_names)}]
d.elementDuration = 6
dsm.set('Config.1.Cc_CurrentConditions', d, 0, 1)
#
"""


def compile_fcst_products(config: "AggregatedConfig") -> str:
    coop_id = config.coop_ids[0] if config.coop_ids else ""
    return f"""d = twc.Data()
d.locName = '{config.name}'
d.coopId = '{coop_id}'
dsm.set('Config.1.Fcst_TextForecast', d, 0, 1)
#
d = twc.Data()
d.locName = '{config.name}'
d.coopId = '{coop_id}'
dsm.set('Config.1.Fcst_DaypartForecast', d, 0, 1)
#
d = twc.Data()
d.locName = '{config.name}'
d.coopId = '{coop_id}'
dsm.set('Config.1.Fcst_ExtendedForecast', d, 0, 1)
#
"""


def compile_3day_forecast(config: "AggregatedConfig") -> str:
    coop_id = config.coop_ids[0] if config.coop_ids else ""
    return f"""d = twc.Data()
d.locName = '{config.name}'
d.coopId = '{coop_id}'
d.prodLabel = '3 Day'
dsm.set('Config.1.Ldl_3DayForecast', d, 0, 1)
#
"""


def compile_traffic_placeholder() -> str:
    return """d = twc.Data()
d.trafficActive = 0
d.trafficReverseActive = [1,1,1,1,1,1,]
d.prodLabel = 'Traffic'
d.routes=[]
d.routeDisplayTime=[]
dsm.set('Config.1.Ldl_TrafficTripTimes', d, 0, 1)
#
d = twc.Data()
d.activeVocal = 0
dsm.set('Config.1.Local_TrafficOverview', d, 0, 1)
dsm.set('Config.1.Local_TrafficFlow', d, 0, 1)
dsm.set('Config.1.Local_TrafficReport', d, 0, 1)
#
"""


def compile_product_statuses() -> str:
    return """#
# Product statuses:
d = twc.Data()
d.activeLocal_AirQualityForecast = 1
d.activeLocal_Climatology = 0
d.activeLocal_GetawayForecast = 1
d.activeLocal_HeatSafetyTips = 1
d.activeLocal_MarineForecast = 0
d.activeLocal_MetroDopplerRadar = 1
d.activeLocal_MetroForecastMap = 1
d.activeLocal_MetroObservationMap = 1
d.activeLocal_OutdoorActivityForecast = 1
d.activeLocal_RadarSatelliteComposite = 1
d.activeLocal_RecordHighLow = 0
d.activeLocal_Satellite = 0
d.activeLocal_SchoolDayWeather = 1
d.activeLocal_Tides = 0
d.activeLocal_TrafficFlow = 0
d.activeLocal_TrafficOverview = 0
d.activeLocal_TrafficReport = 0
d.activeLocal_RegionalDopplerRadar = 1
d.activeLocal_RegionalForecastMap = 1
d.activeLocal_RegionalObservationMap = 1
# region keys
dsm.set('Config.1.DefaultUS.120.2', d, 0)
dsm.set('Config.1.DefaultUS.60.1', d, 0)
dsm.set('Config.1.DefaultUS.90.1', d, 0)
dsm.set('Config.1.DefaultUS.90.0', d, 0)
dsm.set('Config.1.DefaultUS.60.0', d, 0)
dsm.set('Config.1.DefaultUS.120.1', d, 0)
dsm.set('Config.1.DefaultUS.120.0', d, 0)
#
ds.commit()
"""


def compile_playlists() -> str:
    return """#
# PLAYLIST DEFINITIONS
#
d = twc.Data()
d.prodPrefix = 'Local'
d.childPrefixes = ['Tag', 'BackgroundMusic', 'Ldl']
d.units = 'seconds'
d.loadHeuristic = 'loadPriority_v1'
d.overHeuristic = 'overPriority_v1'
d.underHeuristic = 'underPriority_v1'
d.playlist=[
('NWSHeadlines.1',0,7,8,6,1,4,0,["tag1", "bkgMusic1", "ldl1"]),
('NWSHeadlines.2',0,7,7,6,1,5,0,["tag1", "bkgMusic1", "ldl1"]),
('CurrentConditions',0,8,11,6,1,3,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroObservationMap',0,7,10,6,1,21,0,["tag1", "bkgMusic1", "ldl1"]),
('LocalObservations',0,12,14,10,1,19,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalObservationMap',0,7,10,6,1,22,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalDopplerRadar',0,8,8,8,0,8,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroDopplerRadar',0,8,8,0,0,6,0,["tag1", "bkgMusic1", "ldl1"]),
('RadarSatelliteComposite',0,8,8,8,0,17,0,["tag1", "bkgMusic1", "ldl1"]),
('Satellite',0,8,8,8,0,24,0,["tag1", "bkgMusic1", "ldl1"]),
('Climatology',0,7,10,6,1,14,0,["tag1", "bkgMusic1", "ldl1"]),
('Almanac',0,7,10,6,1,15,0,["tag1", "bkgMusic1", "ldl1"]),
('RecordHighLow',0,7,8,6,1,13,0,["tag1", "bkgMusic1", "ldl1"]),
('HeatSafetyTips',0,7,8,6,1,25,0,["tag1", "bkgMusic1", "ldl1"]),
('AirQualityForecast',0,7,10,7,1,16,0,["tag1", "bkgMusic1", "ldl1"]),
('GetawayForecast',0,7,8,6,1,7,0,["tag1", "bkgMusic1", "ldl1"]),
('MarineForecast',0,7,8,6,1,10,0,["tag1", "bkgMusic1", "ldl1"]),
('Tides',0,6,18,6,1,11,0,["tag1", "bkgMusic1", "ldl1"]),
('SchoolDayWeather',0,8,10,7,1,26,0,["tag1", "bkgMusic1", "ldl1"]),
('OutdoorActivityForecast',0,8,10,7,1,27,0,["tag1", "bkgMusic1", "ldl1"]),
('DaypartForecast',0,8,12,6,1,18,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroForecastMap.1',0,8,10,6,1,9,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroForecastMap.2',0,8,10,6,1,20,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalForecastMap.1',0,8,10,6,1,23,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalForecastMap.2',0,8,10,6,1,28,0,["tag1", "bkgMusic1", "ldl1"]),
('TextForecast',0,21,21,18,0,1,0,["tag1", "bkgMusic1", "ldl1"]),
('7DayForecast',0,8,8,6,1,2,0,["tag1", "bkgMusic1", "ldl1"]),
('ExtendedForecast',0,10,12,8,1,29,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.1',0,10,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.2',0,10,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.3',0,10,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.1',0,8,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.2',0,8,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.3',0,8,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficFlow.1',0,7,10,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficFlow.2',0,7,10,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
]
dsm.set('Config.1.Playlist.DefaultUS.60.1', d, 0)
ds.commit()
d = twc.Data()
d.prodPrefix = 'Local'
d.childPrefixes = ['Tag', 'BackgroundMusic', 'Ldl']
d.units = 'seconds'
d.loadHeuristic = 'loadPriority_v1'
d.overHeuristic = 'overPriority_v1'
d.underHeuristic = 'underPriority_v1'
d.playlist=[
('NWSHeadlines.1',0,7,8,6,1,4,0,["tag1", "bkgMusic1", "ldl1"]),
('NWSHeadlines.2',0,7,7,6,1,5,0,["tag1", "bkgMusic1", "ldl1"]),
('CurrentConditions',0,8,11,6,1,3,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroObservationMap',0,7,10,6,1,21,0,["tag1", "bkgMusic1", "ldl1"]),
('LocalObservations',0,12,14,10,1,19,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalObservationMap',0,7,10,6,1,22,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalDopplerRadar',0,8,8,8,0,8,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroDopplerRadar',0,8,8,0,0,6,0,["tag1", "bkgMusic1", "ldl1"]),
('RadarSatelliteComposite',0,8,8,8,0,17,0,["tag1", "bkgMusic1", "ldl1"]),
('Satellite',0,8,8,8,0,24,0,["tag1", "bkgMusic1", "ldl1"]),
('Climatology',0,8,10,7,1,14,0,["tag1", "bkgMusic1", "ldl1"]),
('Almanac',0,8,10,7,1,15,0,["tag1", "bkgMusic1", "ldl1"]),
('RecordHighLow',0,8,8,6,1,13,0,["tag1", "bkgMusic1", "ldl1"]),
('HeatSafetyTips',0,8,8,6,1,25,0,["tag1", "bkgMusic1", "ldl1"]),
('AirQualityForecast',0,8,10,7,1,16,0,["tag1", "bkgMusic1", "ldl1"]),
('GetawayForecast',0,7,10,6,1,7,0,["tag1", "bkgMusic1", "ldl1"]),
('MarineForecast',0,12,14,10,1,10,0,["tag1", "bkgMusic1", "ldl1"]),
('Tides',0,10,10,8,1,11,0,["tag1", "bkgMusic1", "ldl1"]),
('SchoolDayWeather',0,8,10,7,1,26,0,["tag1", "bkgMusic1", "ldl1"]),
('OutdoorActivityForecast',0,8,10,7,1,27,0,["tag1", "bkgMusic1", "ldl1"]),
('DaypartForecast',0,8,12,6,1,18,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroForecastMap.1',0,8,10,7,1,9,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroForecastMap.2',0,8,10,7,1,20,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalForecastMap.1',0,8,10,6,1,23,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalForecastMap.2',0,8,10,6,1,28,0,["tag1", "bkgMusic1", "ldl1"]),
('TextForecast',0,21,21,18,0,1,0,["tag1", "bkgMusic1", "ldl1"]),
('7DayForecast',0,8,8,6,1,2,0,["tag1", "bkgMusic1", "ldl1"]),
('ExtendedForecast',0,10,12,8,1,29,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.1',0,10,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.2',0,10,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.3',0,10,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.1',0,8,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.2',0,8,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.3',0,8,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficFlow.1',0,7,10,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficFlow.2',0,7,10,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
]
dsm.set('Config.1.Playlist.DefaultUS.60.0', d, 0)
ds.commit()
d = twc.Data()
d.prodPrefix = 'Local'
d.childPrefixes = ['Tag', 'BackgroundMusic', 'Ldl']
d.units = 'seconds'
d.loadHeuristic = 'loadPriority_v1'
d.overHeuristic = 'overPriority_v1'
d.underHeuristic = 'underPriority_v1'
d.playlist=[
('NWSHeadlines.1',0,7,8,6,1,4,0,["tag1", "bkgMusic1", "ldl1"]),
('NWSHeadlines.2',0,7,7,6,1,5,0,["tag1", "bkgMusic1", "ldl1"]),
('CurrentConditions',0,8,11,6,1,3,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroObservationMap',0,7,10,6,1,18,0,["tag1", "bkgMusic1", "ldl1"]),
('LocalObservations',0,12,14,10,1,20,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalObservationMap',0,8,10,6,1,18,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalDopplerRadar',0,8,8,8,0,8,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroDopplerRadar',0,12,12,0,0,7,4,["tag1", "bkgMusic1", "ldl1"]),
('RadarSatelliteComposite',0,8,8,8,0,14,4,["tag1", "bkgMusic1", "ldl1"]),
('Satellite',0,20,20,8,0,22,0,["tag1", "bkgMusic1", "ldl1"]),
('Climatology',0,8,10,7,1,15,3,["tag1", "bkgMusic1", "ldl1"]),
('Almanac',0,8,10,7,1,16,3,["tag1", "bkgMusic1", "ldl1"]),
('RecordHighLow',0,6,8,6,1,11,0,["tag1", "bkgMusic1", "ldl1"]),
('HeatSafetyTips',0,8,8,6,1,23,0,["tag1", "bkgMusic1", "ldl1"]),
('AirQualityForecast',0,7,10,6,1,14,0,["tag1", "bkgMusic1", "ldl1"]),
('GetawayForecast',0,8,10,7,1,27,0,["tag1", "bkgMusic1", "ldl1"]),
('MarineForecast',0,10,12,8,1,13,0,["tag1", "bkgMusic1", "ldl1"]),
('Tides',0,8,10,7,1,19,0,["tag1", "bkgMusic1", "ldl1"]),
('SchoolDayWeather',0,8,10,7,1,24,0,["tag1", "bkgMusic1", "ldl1"]),
('OutdoorActivityForecast',0,8,10,7,1,25,0,["tag1", "bkgMusic1", "ldl1"]),
('DaypartForecast',0,8,12,7,1,17,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroForecastMap.1',0,7,10,6,1,9,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroForecastMap.2',0,7,10,6,1,10,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalForecastMap.1',0,8,10,6,1,21,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalForecastMap.2',0,8,10,6,1,26,0,["tag1", "bkgMusic1", "ldl1"]),
('TextForecast',0,28,36,24,0,1,0,["tag1", "bkgMusic1", "ldl1"]),
('7DayForecast',0,12,16,10,1,2,0,["tag1", "bkgMusic1", "ldl1"]),
('ExtendedForecast',0,10,12,8,1,28,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.1',0,8,11,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.2',0,10,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.3',0,10,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.1',0,8,12,6,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.2',0,8,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.3',0,8,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficFlow.1',0,7,10,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficFlow.2',0,7,10,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
]
dsm.set('Config.1.Playlist.DefaultUS.90.1', d, 0)
ds.commit()
d = twc.Data()
d.prodPrefix = 'Local'
d.childPrefixes = ['Tag', 'BackgroundMusic', 'Ldl']
d.units = 'seconds'
d.loadHeuristic = 'loadPriority_v1'
d.overHeuristic = 'overPriority_v1'
d.underHeuristic = 'underPriority_v1'
d.playlist=[
('NWSHeadlines.1',0,7,8,6,1,4,0,["tag1", "bkgMusic1", "ldl1"]),
('NWSHeadlines.2',0,7,7,6,1,5,0,["tag1", "bkgMusic1", "ldl1"]),
('CurrentConditions',0,8,11,6,1,3,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroObservationMap',0,7,10,6,1,6,0,["tag1", "bkgMusic1", "ldl1"]),
('LocalObservations',0,12,14,10,1,20,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalObservationMap',0,8,10,6,1,18,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalDopplerRadar',0,8,8,8,0,8,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroDopplerRadar',0,12,12,0,0,7,4,["tag1", "bkgMusic1", "ldl1"]),
('RadarSatelliteComposite',0,8,8,8,0,14,4,["tag1", "bkgMusic1", "ldl1"]),
('Climatology',0,8,10,7,1,15,3,["tag1", "bkgMusic1", "ldl1"]),
('Almanac',0,8,10,7,1,16,3,["tag1", "bkgMusic1", "ldl1"]),
('RecordHighLow',0,6,8,6,1,11,0,["tag1", "bkgMusic1", "ldl1"]),
('AirQualityForecast',0,7,10,6,1,14,0,["tag1", "bkgMusic1", "ldl1"]),
('MarineForecast',0,10,12,8,1,17,0,["tag1", "bkgMusic1", "ldl1"]),
('Tides',0,8,10,7,1,19,0,["tag1", "bkgMusic1", "ldl1"]),
('DaypartForecast',0,8,10,7,1,17,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroForecastMap.1',0,7,10,6,1,9,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroForecastMap.2',0,7,10,6,1,10,6,["tag1", "bkgMusic1", "ldl1"]),
('TextForecast',0,28,36,24,0,1,0,["tag1", "bkgMusic1", "ldl1"]),
('7DayForecast',0,12,16,10,1,2,0,["tag1", "bkgMusic1", "ldl1"]),
('HeatSafetyTips',0,8,8,6,1,23,0,["tag1", "bkgMusic1", "ldl1"]),
('SchoolDayWeather',0,8,10,7,1,24,0,["tag1", "bkgMusic1", "ldl1"]),
('OutdoorActivityForecast',0,8,10,7,1,25,0,["tag1", "bkgMusic1", "ldl1"]),
('Satellite',0,20,20,8,0,22,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalForecastMap.1',0,8,10,6,1,21,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalForecastMap.2',0,8,10,6,1,26,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.1',0,7,11,5,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('GetawayForecast',0,8,10,7,1,27,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.2',0,10,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.3',0,10,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.1',0,7,12,5,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.2',0,8,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.3',0,8,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('ExtendedForecast',0,10,12,8,1,28,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficFlow.1',0,7,10,5,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficFlow.2',0,7,10,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
]
dsm.set('Config.1.Playlist.DefaultUS.90.0', d, 0)
ds.commit()
d = twc.Data()
d.prodPrefix = 'Local'
d.childPrefixes = ['Tag', 'BackgroundMusic', 'Ldl']
d.units = 'seconds'
d.loadHeuristic = 'loadPriority_v1'
d.overHeuristic = 'overPriority_v1'
d.underHeuristic = 'underPriority_v1'
d.playlist=[
('NWSHeadlines.1',0,7,8,6,1,4,0,["tag1", "bkgMusic1", "ldl1"]),
('NWSHeadlines.2',0,7,7,6,0,5,0,["tag1", "bkgMusic1", "ldl1"]),
('CurrentConditions',0,8,11,6,1,3,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroObservationMap',0,7,10,6,1,21,0,["tag1", "bkgMusic1", "ldl1"]),
('LocalObservations',0,12,14,10,1,6,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalObservationMap',0,7,10,6,1,12,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalDopplerRadar',0,8,8,8,0,11,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroDopplerRadar',0,12,12,0,0,10,4,["tag1", "bkgMusic1", "ldl1"]),
('RadarSatelliteComposite',0,8,8,8,0,17,4,["tag1", "bkgMusic1", "ldl1"]),
('Satellite',0,20,20,8,0,22,4,["tag1", "bkgMusic1", "ldl1"]),
('Climatology',0,8,10,7,1,15,3,["tag1", "bkgMusic1", "ldl1"]),
('Almanac',0,8,10,7,1,15,3,["tag1", "bkgMusic1", "ldl1"]),
('RecordHighLow',0,6,8,6,1,14,0,["tag1", "bkgMusic1", "ldl1"]),
('HeatSafetyTips',0,8,8,6,1,23,0,["tag1", "bkgMusic1", "ldl1"]),
('AirQualityForecast',0,7,10,6,1,16,0,["tag1", "bkgMusic1", "ldl1"]),
('GetawayForecast',0,10,12,9,1,7,0,["tag1", "bkgMusic1", "ldl1"]),
('MarineForecast',0,10,12,8,1,8,0,["tag1", "bkgMusic1", "ldl1"]),
('Tides',0,8,10,7,1,9,0,["tag1", "bkgMusic1", "ldl1"]),
('SchoolDayWeather',0,8,10,7,1,24,0,["tag1", "bkgMusic1", "ldl1"]),
('OutdoorActivityForecast',0,8,10,7,1,25,0,["tag1", "bkgMusic1", "ldl1"]),
('DaypartForecast',0,8,12,7,1,18,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroForecastMap.1',0,7,10,6,1,19,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroForecastMap.2',0,7,10,6,1,20,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalForecastMap.1',0,7,10,6,1,13,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalForecastMap.2',0,7,10,6,1,26,0,["tag1", "bkgMusic1", "ldl1"]),
('TextForecast',0,28,36,24,0,1,0,["tag1", "bkgMusic1", "ldl1"]),
('7DayForecast',0,12,16,10,1,2,0,["tag1", "bkgMusic1", "ldl1"]),
('ExtendedForecast',0,10,12,8,1,27,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.1',0,9,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.2',0,9,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.3',0,9,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.1',0,9,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.2',0,9,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.3',0,9,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficFlow.1',0,8,10,6,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficFlow.2',0,8,10,6,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
]
dsm.set('Config.1.Playlist.DefaultUS.120.2', d, 0)
ds.commit()
d = twc.Data()
d.prodPrefix = 'Local'
d.childPrefixes = ['Tag', 'BackgroundMusic', 'Ldl']
d.units = 'seconds'
d.loadHeuristic = 'loadPriority_v1'
d.overHeuristic = 'overPriority_v1'
d.underHeuristic = 'underPriority_v1'
d.playlist=[
('NWSHeadlines.1',0,7,8,6,1,4,0,["tag1", "bkgMusic1", "ldl1"]),
('NWSHeadlines.2',0,7,7,6,1,5,0,["tag1", "bkgMusic1", "ldl1"]),
('CurrentConditions',0,8,11,6,1,3,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroObservationMap',0,7,10,6,1,19,0,["tag1", "bkgMusic1", "ldl1"]),
('LocalObservations',0,12,14,10,1,6,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalObservationMap',0,7,10,6,1,17,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalDopplerRadar',0,8,8,8,0,11,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroDopplerRadar',0,12,12,0,0,10,4,["tag1", "bkgMusic1", "ldl1"]),
('RadarSatelliteComposite',0,8,8,8,0,15,4,["tag1", "bkgMusic1", "ldl1"]),
('Satellite',0,20,20,8,0,22,0,["tag1", "bkgMusic1", "ldl1"]),
('Climatology',0,8,10,7,1,13,3,["tag1", "bkgMusic1", "ldl1"]),
('Almanac',0,8,10,7,1,13,3,["tag1", "bkgMusic1", "ldl1"]),
('RecordHighLow',0,6,8,6,1,12,0,["tag1", "bkgMusic1", "ldl1"]),
('HeatSafetyTips',0,8,8,6,1,23,0,["tag1", "bkgMusic1", "ldl1"]),
('AirQualityForecast',0,7,10,6,1,14,0,["tag1", "bkgMusic1", "ldl1"]),
('GetawayForecast',0,10,12,9,1,7,0,["tag1", "bkgMusic1", "ldl1"]),
('MarineForecast',0,10,12,8,1,8,0,["tag1", "bkgMusic1", "ldl1"]),
('Tides',0,8,10,7,1,9,0,["tag1", "bkgMusic1", "ldl1"]),
('SchoolDayWeather',0,8,10,7,1,24,0,["tag1", "bkgMusic1", "ldl1"]),
('OutdoorActivityForecast',0,8,10,7,1,25,0,["tag1", "bkgMusic1", "ldl1"]),
('DaypartForecast',0,8,12,7,1,16,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroForecastMap.1',0,7,10,6,1,20,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroForecastMap.2',0,7,10,6,1,21,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalForecastMap.1',0,7,10,6,1,18,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalForecastMap.2',0,7,10,6,1,26,0,["tag1", "bkgMusic1", "ldl1"]),
('TextForecast',0,28,36,24,0,1,0,["tag1", "bkgMusic1", "ldl1"]),
('7DayForecast',0,12,16,10,1,2,0,["tag1", "bkgMusic1", "ldl1"]),
('ExtendedForecast',0,10,12,8,1,27,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.1',0,10,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.2',0,10,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.3',0,10,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.1',0,10,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.2',0,10,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.3',0,10,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficFlow.1',0,10,10,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficFlow.2',0,10,10,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
]
dsm.set('Config.1.Playlist.DefaultUS.120.1', d, 0)
ds.commit()
d = twc.Data()
d.prodPrefix = 'Local'
d.childPrefixes = ['Tag', 'BackgroundMusic', 'Ldl']
d.units = 'seconds'
d.loadHeuristic = 'loadPriority_v1'
d.overHeuristic = 'overPriority_v1'
d.underHeuristic = 'underPriority_v1'
d.playlist=[
('NWSHeadlines.1',0,7,8,6,1,4,0,["tag1", "bkgMusic1", "ldl1"]),
('NWSHeadlines.2',0,7,7,6,1,5,0,["tag1", "bkgMusic1", "ldl1"]),
('CurrentConditions',0,8,11,6,1,3,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroObservationMap',0,7,10,6,1,21,0,["tag1", "bkgMusic1", "ldl1"]),
('LocalObservations',0,12,14,10,1,6,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalObservationMap',0,7,10,6,1,12,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalDopplerRadar',0,8,8,8,0,11,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroDopplerRadar',0,12,12,0,0,10,4,["tag1", "bkgMusic1", "ldl1"]),
('RadarSatelliteComposite',0,8,8,8,0,17,4,["tag1", "bkgMusic1", "ldl1"]),
('Satellite',0,20,20,8,0,22,0,["tag1", "bkgMusic1", "ldl1"]),
('Climatology',0,8,10,7,1,15,3,["tag1", "bkgMusic1", "ldl1"]),
('Almanac',0,8,10,7,1,15,3,["tag1", "bkgMusic1", "ldl1"]),
('RecordHighLow',0,6,8,6,1,14,0,["tag1", "bkgMusic1", "ldl1"]),
('HeatSafetyTips',0,8,8,6,1,23,0,["tag1", "bkgMusic1", "ldl1"]),
('AirQualityForecast',0,7,10,6,1,16,0,["tag1", "bkgMusic1", "ldl1"]),
('GetawayForecast',0,10,12,9,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('MarineForecast',0,10,12,8,1,8,0,["tag1", "bkgMusic1", "ldl1"]),
('Tides',0,8,10,7,1,9,0,["tag1", "bkgMusic1", "ldl1"]),
('SchoolDayWeather',0,8,10,7,1,24,0,["tag1", "bkgMusic1", "ldl1"]),
('OutdoorActivityForecast',0,8,10,7,1,25,0,["tag1", "bkgMusic1", "ldl1"]),
('DaypartForecast',0,8,12,7,1,18,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroForecastMap.1',0,7,10,6,1,19,0,["tag1", "bkgMusic1", "ldl1"]),
('MetroForecastMap.2',0,7,10,6,1,20,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalForecastMap.1',0,7,10,6,1,13,0,["tag1", "bkgMusic1", "ldl1"]),
('RegionalForecastMap.2',0,7,10,6,1,26,0,["tag1", "bkgMusic1", "ldl1"]),
('TextForecast',0,28,36,24,0,1,0,["tag1", "bkgMusic1", "ldl1"]),
('7DayForecast',0,12,16,10,1,2,0,["tag1", "bkgMusic1", "ldl1"]),
('ExtendedForecast',0,10,12,8,1,27,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.1',0,10,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.2',0,10,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficOverview.3',0,10,11,8,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.1',0,10,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.2',0,10,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficReport.3',0,10,12,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficFlow.1',0,10,10,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
('TrafficFlow.2',0,10,10,7,1,99,0,["tag1", "bkgMusic1", "ldl1"]),
]
dsm.set('Config.1.Playlist.DefaultUS.120.0', d, 0)
ds.commit()
#
"""


def compile_ldl_playlist() -> str:
    return """d = twc.Data()
d.prodPrefix = 'Ldl'
d.childPrefixes = ['LdlMenu', 'TimeTemp', 'Logo']
d.units = 'seconds'
d.loadHeuristic = 'loadPriority_v1'
d.overHeuristic = 'overPriority_v1'
d.underHeuristic = 'underPriority_v1'
d.playlist=[
('IntroAnimation',0,2,2,2,0,1,0,["ldlMenu1", "timeTemp1", "logo1"]),
('LASCrawl',0,4,120,4,0,1,0,["ldlMenu1", "timeTemp1", "logo1"]),
('HurricaneWatch',0,4,12,4,0,1,0,["ldlMenu1", "timeTemp1", "logo1"]),
('TornadoWatch',0,6,480,6,0,1,0,["ldlMenu1", "timeTemp1", "logo1"]),
('SevereThunderstormWatch',0,6,480,6,0,1,0,["ldlMenu1", "timeTemp1", "logo1"]),
('CurrentObs',3,4,44,4,1,2,0,["ldlMenu1", "timeTemp1", "logo1"]),
('Void',0,1,120,1,1,1,0,["ldlMenu1", "timeTemp1", "logo1"]),
]
dsm.set('Config.1.Playlist.Ldl.ldl1', d, 0)
ds.commit()
#
"""


def compile_fcst_playlist() -> str:
    return """d = twc.Data()
d.prodPrefix='Fcst'
d.childPrefixes=[]
d.units='seconds'
d.loadHeuristic='loadPriorityOneOnly_v1'
d.overHeuristic='overPriority_v1'
d.underHeuristic='underPriority_v1'
d.playlist=[
('TextForecast.1',0,14,60,14,1,1,0,[]),
('TextForecast.2',0,14,60,14,1,1,0,[]),
('DaypartForecast',0,14,60,14,1,1,0,[]),
('ExtendedForecast',0,14,60,14,1,1,0,[]),
('Unavailable',0,1,60,1,1,2,0,[]),
]
dsm.set('Config.1.Playlist.Fcst.fcst1', d, 0)
#
ds.commit()
d = twc.Data()
d.prodPrefix='Local'
d.childPrefixes=["Cc", "Radar", "Fcst", "Logo"]
d.units='percent'
d.loadHeuristic='loadPriority_v1'
d.overHeuristic='overPriority_v1'
d.underHeuristic='underPriority_v1'
d.playlist=[
('SqueezebackFade',0,100,100,100,1,1,0,["cc1","radar1","fcst1","logo1"]),
]
dsm.set('Config.1.Playlist.DefaultUS.57.0', d, 0)
#
ds.commit()
#
"""


def compile_national_ldl_playlist() -> str:
    return """d = twc.Data()
d.prodPrefix = 'NationalLdl'
d.childPrefixes = ['Logo']
d.units = 'seconds'
d.loadHeuristic = 'loadPriority_v1'
d.overHeuristic = 'overPriority_v1'
d.underHeuristic = 'underPriority_v1'
d.playlist=[
('IntroAnimation',0,2,2,2,0,1,0,["nationalLdlLogo1"]),
('WeatherBulletin',0,5,5,0,0,1,0,["nationalLdlLogo1"]),
('DopplerRadar',0,8,8,4,0,1,0,["nationalLdlLogo1"]),
('CurrentConditions',0,12,12,12,0,1,0,["nationalLdlLogo1"]),
('HourlyForecast',0,0,0,0,0,1,0,["nationalLdlLogo1"]),
('DaypartForecast',0,30,30,30,0,1,0,["nationalLdlLogo1"]),
('5DayForecast',0,11,11,11,0,1,0,["nationalLdlLogo1"]),
('CurrentConditions',1,12,12,0,0,1,0,["nationalLdlLogo1"]),
('36HourForecast',1,10,10,0,0,1,0,["nationalLdlLogo1"]),
('5DayForecast',1,11,11,0,0,1,0,["nationalLdlLogo1"]),
('CurrentConditions',2,12,12,0,0,1,0,["nationalLdlLogo1"]),
('36HourForecast',2,10,10,0,0,1,0,["nationalLdlLogo1"]),
('5DayForecast',2,11,11,0,0,1,0,["nationalLdlLogo1"]),
('CurrentConditions',3,12,12,0,0,1,0,["nationalLdlLogo1"]),
('36HourForecast',3,10,10,0,0,1,0,["nationalLdlLogo1"]),
('5DayForecast',3,11,11,0,0,1,0,["nationalLdlLogo1"]),
('CurrentConditions',4,12,12,0,0,1,0,["nationalLdlLogo1"]),
('36HourForecast',4,10,10,0,0,1,0,["nationalLdlLogo1"]),
('5DayForecast',4,11,11,0,0,1,0,["nationalLdlLogo1"]),
('CurrentConditions',5,12,12,0,0,1,0,["nationalLdlLogo1"]),
('36HourForecast',5,10,10,0,0,1,0,["nationalLdlLogo1"]),
('5DayForecast',5,11,11,0,0,1,0,["nationalLdlLogo1"]),
('WeatherBulletin',0,5,5,0,0,1,0,["nationalLdlLogo1"]),
('DopplerRadar',0,8,8,4,0,1,0,["nationalLdlLogo1"]),
('CurrentConditions',0,12,12,12,0,1,0,["nationalLdlLogo1"]),
('HourlyForecast',0,0,0,0,0,1,0,["nationalLdlLogo1"]),
('TextForecast.1',0,18,18,3,0,1,0,["nationalLdlLogo1"]),
('TextForecast.2',0,18,18,3,0,1,0,["nationalLdlLogo1"]),
('TextForecast.3',0,18,18,3,0,1,0,["nationalLdlLogo1"]),
('5DayForecast',0,11,11,11,0,1,0,["nationalLdlLogo1"]),
('CurrentConditions',1,12,12,0,0,1,0,["nationalLdlLogo1"]),
('36HourForecast',1,10,10,0,0,1,0,["nationalLdlLogo1"]),
('5DayForecast',1,11,11,0,0,1,0,["nationalLdlLogo1"]),
('CurrentConditions',2,12,12,0,0,1,0,["nationalLdlLogo1"]),
('36HourForecast',2,10,10,0,0,1,0,["nationalLdlLogo1"]),
('5DayForecast',2,11,11,0,0,1,0,["nationalLdlLogo1"]),
('CurrentConditions',3,12,12,0,0,1,0,["nationalLdlLogo1"]),
('36HourForecast',3,10,10,0,0,1,0,["nationalLdlLogo1"]),
('5DayForecast',3,11,11,0,0,1,0,["nationalLdlLogo1"]),
('CurrentConditions',4,12,12,0,0,1,0,["nationalLdlLogo1"]),
('36HourForecast',4,10,10,0,0,1,0,["nationalLdlLogo1"]),
('5DayForecast',4,11,11,0,0,1,0,["nationalLdlLogo1"]),
('CurrentConditions',5,12,12,0,0,1,0,["nationalLdlLogo1"]),
('36HourForecast',5,10,10,0,0,1,0,["nationalLdlLogo1"]),
('5DayForecast',5,11,11,0,0,1,0,["nationalLdlLogo1"]),
('Void',0,1,600,1,1,1,0,["nationalLdlLogo1"]),
]
dsm.set('Config.1.Playlist.NationalLdl.nationalLdlUp', d, 0)
ds.commit()
d = twc.Data()
d.prodPrefix = 'NationalLdl'
d.childPrefixes = ['Logo']
d.units = 'seconds'
d.loadHeuristic = 'loadPriority_v1'
d.overHeuristic = 'overPriority_v1'
d.underHeuristic = 'underPriority_v1'
d.playlist=[
('IntroAnimationSmall',0,2,2,2,0,1,0,["nationalLdlLogo1"]),
('CurrentConditionsSmall',0,12,12,4,0,1,0,["nationalLdlLogo1"]),
('DaypartForecastSmall',0,16,16,8,0,1,0,["nationalLdlLogo1"]),
('5DayForecastSmall',0,20,20,10,0,1,0,["nationalLdlLogo1"]),
('CurrentConditionsSmall',1,12,12,0,0,1,0,["nationalLdlLogo1"]),
('DaypartForecastSmall',1,16,16,0,0,1,0,["nationalLdlLogo1"]),
('5DayForecastSmall',1,20,20,0,0,1,0,["nationalLdlLogo1"]),
('CurrentConditionsSmall',2,12,12,0,0,1,0,["nationalLdlLogo1"]),
('DaypartForecastSmall',2,16,16,0,0,1,0,["nationalLdlLogo1"]),
('5DayForecastSmall',2,20,20,0,0,1,0,["nationalLdlLogo1"]),
('CurrentConditionsSmall',3,12,12,0,0,1,0,["nationalLdlLogo1"]),
('DaypartForecastSmall',3,16,16,0,0,1,0,["nationalLdlLogo1"]),
('5DayForecastSmall',3,20,20,0,0,1,0,["nationalLdlLogo1"]),
('CurrentConditionsSmall',4,12,12,0,0,1,0,["nationalLdlLogo1"]),
('DaypartForecastSmall',4,16,16,0,0,1,0,["nationalLdlLogo1"]),
('5DayForecastSmall',4,20,20,0,0,1,0,["nationalLdlLogo1"]),
('CurrentConditionsSmall',5,12,12,0,0,1,0,["nationalLdlLogo1"]),
('DaypartForecastSmall',5,16,16,0,0,1,0,["nationalLdlLogo1"]),
('5DayForecastSmall',5,20,20,0,0,1,0,["nationalLdlLogo1"]),
('Void',0,1,600,1,1,1,0,["nationalLdlLogo1"]),
]
dsm.set('Config.1.Playlist.NationalLdl.nationalLdlUpB', d, 0)
ds.commit()
#
"""


def compile_national_ldl_schedule() -> str:
    return """d = [
    [[(0,0), (23,59), 'NationalLdl.nationalLdlUp',],],
    [[(0,0), (23,59), 'NationalLdl.nationalLdlUp',],],
    [[(0,0), (23,59), 'NationalLdl.nationalLdlUp',],],
    [[(0,0), (23,59), 'NationalLdl.nationalLdlUp',],],
    [[(0,0), (23,59), 'NationalLdl.nationalLdlUp',],],
    [[(0,0), (23,59), 'NationalLdl.nationalLdlUp',],],
    [[(0,0), (23,59), 'NationalLdl.nationalLdlUp',],],
]
dsm.set('Config.1.Playlist.NationalLdl.scheduleA', d, 0)
d = [
    [[(0,0), (23,59), 'NationalLdl.nationalLdlUpB',],],
    [[(0,0), (23,59), 'NationalLdl.nationalLdlUpB',],],
    [[(0,0), (23,59), 'NationalLdl.nationalLdlUpB',],],
    [[(0,0), (23,59), 'NationalLdl.nationalLdlUpB',],],
    [[(0,0), (23,59), 'NationalLdl.nationalLdlUpB',],],
    [[(0,0), (23,59), 'NationalLdl.nationalLdlUpB',],],
    [[(0,0), (23,59), 'NationalLdl.nationalLdlUpB',],],
]
dsm.set('Config.1.Playlist.NationalLdl.scheduleB', d, 0)
#
"""


def compile_footer() -> str:
    return """## End of SCMT Configuration
#
ds.commit()
Log.info('scmt config finished')
"""


def generate_domestic_config(
    config: "AggregatedConfig",
    all_records: list["LocationRecord"],
    random_cable_name: str,
    random_star_id: int,
    timezone: str,
) -> str:
    sections = [
        compile_header(),
        compile_map_interest_lists(config),
        compile_interest_list(config),
        compile_metadata(config, random_cable_name, random_star_id, timezone),
        compile_override_block(),
        compile_airport_data(config, all_records),
        compile_snowboard_data(),
        compile_non_image_maps(),
        compile_vocal_schedule(),
        compile_scmt_removes(),
        compile_heat_safety(config),
        compile_uv_forecast(config),
        compile_daily_forecast(config, all_records),
        compile_national_ldl_products(config, all_records),
        compile_local_daypart_forecast(config),
        compile_nws_headlines(config),
        compile_ldl_current_obs(config, all_records),
        compile_weather_bulletin(config),
        compile_outdoor_activity(config),
        compile_extended_forecast(config),
        compile_hourly_forecast(config),
        compile_7day_forecast(config),
        compile_school_day_weather(config),
        compile_airport_delays(config, all_records),
        compile_getaway_forecast(config, all_records),
        compile_air_quality(config),
        compile_text_forecast(config),
        compile_time_temp(config),
        compile_current_conditions(config),
        compile_local_observations(config, all_records),
        compile_hurricane_watch(),
        compile_climatology(config),
        compile_record_high_low(config),
        compile_tides(config),
        compile_marine_forecast(config),
        compile_event_forecast(config),
        compile_travel_forecast(config, all_records),
        compile_almanac(config),
        compile_star_id_message(),
        compile_cc_current_conditions(config),
        compile_fcst_products(config),
        compile_3day_forecast(config),
        compile_traffic_placeholder(),
        compile_product_statuses(),
        compile_playlists(),
        compile_ldl_playlist(),
        compile_fcst_playlist(),
        compile_national_ldl_playlist(),
        compile_national_ldl_schedule(),
        compile_footer(),
    ]
    
    return "\n".join(section for section in sections if section)
