from datetime import datetime
import random

def compile_config(config) -> str:
    random_star_id = random.randint(100000, 999999)

    random_cable_names = [
        "I HATE COMCAST CORPORATION",
        "NOT MARICOM",
        "FOREST CLEARING COMMUNICATIONS",
        "WHO CARES ABOUT THIS THEY ARE ALL OWNED BY ONE BIG CORPORATION ANYWAYS",
        "OPEN YOUR MIND. OPEN YOUR EYES",
        "STEVEN HERE",
        "FEMBOYTELECOM",
        "GENERICABLE INC.",
        "WHOLLY OWNED BY MIST WEATHER MEDIA",
        "ZESTNETTV",
        "ZACHNET TV",
        "The67TV",
        "HI MY NAME IS AUSTIN AND IM A PEDOPHILE, INC",
        "GENERICABLE SUCKS",
        "I HATE ROGERS XFINITY",
        "DECENTRALIZE TELECOMMUNICATIONS",
        "meowwww",
    ]
    random_cable_name = random.choice(random_cable_names)

    sections = []
    sections.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>")
    sections.append("<!-- Generated on {} -->".format(datetime.now().strftime("%Y-%m-%d %H:%M:%S")))
    sections.append("<!-- Machine Product Config File for IntelliStar 2  -->")
    sections.append("<!-- Generated by IntelliStar Config Generator by @sspwxr (raii) -->")
    sections.append("<Config>")
    sections.append("  <ConfigDef>")
    sections.append("    <ConfigItems>")
    sections.append("      <ConfigItem key=\"AffiliateLogoId\" value=\"domestic\\affiliateLogos\\BlankLogo.tif\" />")
    sections.append("      <ConfigItem key=\"AffiliateText1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"AffiliateText2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"Airport1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"Airport1_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"Airport1_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"Airport2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"Airport2_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"Airport2_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"Airport3\" value=\"\" />")
    sections.append("      <ConfigItem key=\"Airport3_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"Airport3_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"AreaServed\" value=\"\" />")
    sections.append("      <ConfigItem key=\"AuthorizationCode\" value=\"y\" />")
    sections.append(f"      <ConfigItem key=\"AuthorizationDate\" value=\"{datetime.now().strftime('%m')}/{datetime.now().strftime('%d')}/{datetime.now().strftime('%Y')}\" />")
    sections.append("      <ConfigItem key=\"BeachLocation\" value=\"\" />")
    sections.append("      <ConfigItem key=\"BeachLocation_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"BeachLocation_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"ChannelId\" value=\"\" />")
    sections.append("      <ConfigItem key=\"ChannelNumber\" value=\"\" />")
    sections.append("      <ConfigItem key=\"ChannelText\" value=\"\" />")
    sections.append(f"      <ConfigItem key=\"CityName\" value=\"{config.name}\" />")
    sections.append("      <ConfigItem key=\"ConnectMethod\" value=\"\" />")
    sections.append(f"      <ConfigItem key=\"CountryCode\" value=\"{config.country_code}\" />")
    sections.append("      <ConfigItem key=\"DataFromHeadendNb\" value=\"\" />")
    sections.append("      <ConfigItem key=\"disableLocalization\" value=\"False\" />")
    sections.append("      <ConfigItem key=\"disableLOCL\" value=\"\" />")
    sections.append("      <ConfigItem key=\"DisplayLogoFlag\" value=\"\" />")
    sections.append("      <ConfigItem key=\"DmaCode\" value=\"\" />")
    sections.append("      <ConfigItem key=\"DmaName\" value=\"\" />")
    sections.append("      <ConfigItem key=\"ExternalIpAddress\" value=\"\" />")
    sections.append("      <ConfigItem key=\"FedFromHeadend\" value=\"\" />")
    sections.append("      <ConfigItem key=\"FedFromHeadendName\" value=\"\" />")
    sections.append("      <ConfigItem key=\"FrontChannelGateway\" value=\"\" />")
    sections.append("      <ConfigItem key=\"FrontChannelIpAddress\" value=\"\" />")
    sections.append("      <ConfigItem key=\"FrontChannelNetMask\" value=\"\" />")
    sections.append("      <ConfigItem key=\"GatewayAddress\" value=\"\" />")
    sections.append("      <ConfigItem key=\"HeadendAddress\" value=\"\" />")
    sections.append(f"      <ConfigItem key=\"HeadendId\" value=\"{random_star_id}\" />")
    sections.append(f"      <ConfigItem key=\"HeadendName\" value=\"HD XD - {config.name} - HD XD\" />")
    sections.append("      <ConfigItem key=\"LocalDns1Address\" value=\"\" />")
    sections.append("      <ConfigItem key=\"LocalDns2Address\" value=\"\" />")
    sections.append("      <ConfigItem key=\"LocalIpAddress\" value=\"\" />")
    sections.append("      <ConfigItem key=\"LocalOcmMkt\" value=\"\" />")
    for i in range(1, 9):
        if i - 1 < len(config.nearby_location_ids):
            loc = config.nearby_location_ids[i - 1]
            nearby_value = f"1_{config.country_code}_{loc}"
        else:
            nearby_value = ""
        sections.append(f"      <ConfigItem key=\"LocalRadarCity{i}\" value=\"{nearby_value}\" />")
        sections.append(f"      <ConfigItem key=\"LocalRadarCity{i}_1\" value=\"\" />")
        sections.append(f"      <ConfigItem key=\"LocalRadarCity{i}_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"LogoCd\" value=\"\" />")
    sections.append("      <ConfigItem key=\"LogoDescription\" value=\"\" />")
    for i in range(1, 9):
        if i - 1 < len(config.nearby_location_ids):
            loc = config.nearby_location_ids[i - 1]
            nearby_value = f"1_{config.country_code}_{loc}"
        else:
            nearby_value = ""
        sections.append(f"      <ConfigItem key=\"MapCity{i}\" value=\"{nearby_value}\" />")
        sections.append(f"      <ConfigItem key=\"MapCity{i}_1\" value=\"\" />")
        sections.append(f"      <ConfigItem key=\"MapCity{i}_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"MasterUnitAddress\" value=\"\" />")
    for i in range(1, 9):
        if i - 1 < len(config.nearby_location_ids):
            loc = config.nearby_location_ids[i - 1]
            nearby_value = f"1_{config.country_code}_{loc}"
        else:
            nearby_value = ""
        sections.append(f"      <ConfigItem key=\"MetroMapCity{i}\" value=\"{nearby_value}\" />")
        sections.append(f"      <ConfigItem key=\"MetroMapCity{i}_1\" value=\"\" />")
        sections.append(f"      <ConfigItem key=\"MetroMapCity{i}_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"MsoCode\" value=\"00000\" />")
    sections.append(f"      <ConfigItem key=\"MsoName\" value=\"{random_cable_name}\" />")
    for i in range(1, 9):
        if i - 1 < len(config.nearby_location_ids):
            loc = config.nearby_location_ids[i - 1]
            nearby_value = f"1_{config.country_code}_{loc}"
        else:
            nearby_value = ""
        sections.append(f"      <ConfigItem key=\"NearbyLocation{i}\" value=\"{nearby_value}\" />")
        sections.append(f"      <ConfigItem key=\"NearbyLocation{i}_1\" value=\"\" />")
        sections.append(f"      <ConfigItem key=\"NearbyLocation{i}_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"NetMask\" value=\"255.255.255.0\" />")
    sections.append("      <ConfigItem key=\"OcmOn8CityCode\" value=\"\" />")
    sections.append("      <ConfigItem key=\"OcmOn8DataPid\" value=\"\" />")
    sections.append("      <ConfigItem key=\"OcmOn8Enabled\" value=\"\" />")
    sections.append("      <ConfigItem key=\"OcmOn8MsgIngesterMulticastIpAddress\" value=\"\" />")
    sections.append("      <ConfigItem key=\"OcmOn8MsgIngesterMulticastPort\" value=\"\" />")
    sections.append("      <ConfigItem key=\"OnAirName\" value=\"\" />")
    sections.append(f"      <ConfigItem key=\"PrimaryLatitudeLongitude\" value=\"W{abs(config.lon)}-N{config.lat}\" />")
    sections.append("      <ConfigItem key=\"PrimaryLatitudeLongitude_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"PrimaryLatitudeLongitude_2\" value=\"\" />")
    sections.append(f"      <ConfigItem key=\"PrimaryLocation\" value=\"1_{config.country_code}_{config.location_id}\" />")
    sections.append("      <ConfigItem key=\"PrimaryLocation_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"PrimaryLocation_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"primaryMarineZone\" value=\"\" />")
    sections.append(f"      <ConfigItem key=\"primaryCounty\" value=\"{config.county_ids[0]}\" />")
    sections.append(f"      <ConfigItem key=\"primaryZone\" value=\"{config.zone_ids[0]}\" />")
    sections.append("      <ConfigItem key=\"PrimaryWMO\" value=\"\" />")
    sections.append("      <ConfigItem key=\"RadioLogo\" value=\"domestic\\radioLogos\\NationalLogo_Dma_County.tif\" />")
    for i in range(1, 9):
        if i - 1 < len(config.nearby_location_ids):
            loc = config.nearby_location_ids[i - 1]
            nearby_value = f"1_{config.country_code}_{loc}"
        else:
            nearby_value = ""
        sections.append(f"      <ConfigItem key=\"RegionalMapCity1{i}\" value=\"{nearby_value}\" />")
        sections.append(f"      <ConfigItem key=\"RegionalMapCity1{i}_1\" value=\"\" />")
        sections.append(f"      <ConfigItem key=\"RegionalMapCity1{i}_2\" value=\"\" />")
    sections.append(f"      <ConfigItem key=\"secondaryCounties\" value=\"{','.join(config.county_ids[1:])}\" />")
    sections.append(f"      <ConfigItem key=\"secondaryZones\" value=\"{','.join(config.zone_ids[1:])}\" />")
    sections.append("      <ConfigItem key=\"serialNumber\" value=\"XD00000\" />")
    sections.append("      <ConfigItem key=\"Service\" value=\"\" />")
    sections.append(f"      <ConfigItem key=\"StateCode\" value=\"{config.state_code}\" />")
    sections.append("      <ConfigItem key=\"StatesServed\" value=\"\" />")
    sections.append("      <ConfigItem key=\"SummerGetawayLocation1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"SummerGetawayLocation1_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"SummerGetawayLocation1_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"SummerGetawayLocation2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"SummerGetawayLocation2_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"SummerGetawayLocation2_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"SummerGetawayLocation3\" value=\"\" />")
    sections.append("      <ConfigItem key=\"SummerGetawayLocation3_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"SummerGetawayLocation3_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"SystemId\" value=\"\" />")
    sections.append(f"      <ConfigItem key=\"SystemName\" value=\"{config.name}\" />")
    sections.append("      <ConfigItem key=\"TerminationDate\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation1_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation1_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation2_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation2_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation3\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation3_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation3_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation4\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation4_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation4_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation5\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation5_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation5_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation6\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation6_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation6_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation7\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation7_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation7_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation8\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation8_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TideStation8_2\" value=\"\" />")
    sections.append(f"      <ConfigItem key=\"timeZone\" value=\"{config.full_time_zone}\" />")
    sections.append("      <ConfigItem key=\"TrafficIncidentPrimaryRadius\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TrafficIncidentSecondaryRadius\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TrafficKeyRoute1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TrafficKeyRoute2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TrafficKeyRoute3\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TrafficKeyRoute4\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TrafficKeyRoute5\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TrafficKeyRoute6\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TravelCity1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TravelCity1_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TravelCity1_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TravelCity2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TravelCity2_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TravelCity2_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TravelCity3\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TravelCity3_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TravelCity3_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TravelCity4\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TravelCity4_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TravelCity4_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TravelCity5\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TravelCity5_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"TravelCity5_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"WinterGetawayLocation1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"WinterGetawayLocation1_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"WinterGetawayLocation1_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"WinterGetawayLocation2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"WinterGetawayLocation2_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"WinterGetawayLocation2_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"WinterGetawayLocation3\" value=\"\" />")
    sections.append("      <ConfigItem key=\"WinterGetawayLocation3_1\" value=\"\" />")
    sections.append("      <ConfigItem key=\"WinterGetawayLocation3_2\" value=\"\" />")
    sections.append("      <ConfigItem key=\"ZipCode\" value=\"\" />")
    sections.append("    </ConfigItems>")
    sections.append("  </ConfigDef>")
    sections.append("</Config>")
    
    return "\n".join(sections)
